"""The site's baked figures must be exactly what ``reports/`` measured.

Every number the results sections print comes from
``web/src/generated/reports.ts``, which ``scripts/build_site_data.py`` bakes from
``reports/*.json`` and the model card. This module is what stops that artefact
drifting from its sources, and it is built against a failure this repository has
already met once: **byte equality between a generator and its own output is a
tautology.** An exporter that publishes only a subset of its inputs passes a
byte-equality check happily, because regenerating reproduces the same hole.

So there are four independent mechanisms here, not one:

1. byte equality with a fresh bake -- catches a hand-edited artefact and a report
   edited without re-baking, and both directions are asserted mechanically below
   rather than argued for in a comment;
2. a hand-written coverage table -- pointers into the reports that MUST be
   published, written here and not read from the generator, so a field silently
   dropped from the spec fails even though the artefact still round-trips;
3. a containment sweep -- every published scalar must be a value that actually
   occurs in its own source report, so a figure cannot be invented or mistyped;
4. the derived values, recomputed here from the source JSON with the formula
   written out again, so a bug in the generator's arithmetic does not become the
   page's arithmetic.

Plus the redaction: no absolute km/h derived from ``motorway-a40.webm`` may reach
the page. That clip has no independent along-road anchor, its along-road scale is
bracketed at -33 %/+0 %, and the engine returns ``None`` for speed on it by
design -- see ``reports/speed_real.json``. The guard is asserted over the baked
artefact, the authored HTML and the published ``docs/`` alike.
"""

import json
import math
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
GENERATOR = ROOT / "scripts" / "build_site_data.py"
REPORTS_DIR = ROOT / "reports"
MODEL_CARD = ROOT / "web" / "public" / "models" / "MODEL_CARD.md"
TS_GENERATED = ROOT / "web" / "src" / "generated" / "reports.ts"

HEADER = "// generated by scripts/build_site_data.py — do not edit"

#: Floors, so no assertion in this module can pass by finding nothing. Two empty
#: structures compare equal, so without these an emptied spec would satisfy byte
#: equality, the containment sweep and the coverage table alike.
MINIMUM_PUBLISHED_SCALARS = 900
MINIMUM_SECTIONS = 8

#: The published figure this project must never restate. It is the maximum speed
#: the parity fixture recorded on the flagship clip, and it is in reports/ for the
#: cross-surface comparison's own purposes -- but the clip ships uncalibrated, so
#: as a published figure it would assert a scale the survey withdrew.
FORBIDDEN_SPEED_KEY = "maxSpeedKmh"


def _run(*args: str) -> subprocess.CompletedProcess:
    """Drive the generator the way a developer does: as a script."""
    return subprocess.run(
        [sys.executable, str(GENERATOR), *args],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )


def _bake(out_path: Path, reports: Path | None = None, card: Path | None = None):
    args = ["--out", str(out_path)]
    if reports is not None:
        args += ["--reports", str(reports)]
    if card is not None:
        args += ["--model-card", str(card)]
    return _run(*args)


def _bake_or_fail(out_path: Path) -> bytes:
    result = _bake(out_path)
    assert result.returncode == 0, (
        f"the generator failed on the committed reports:\n"
        f"{result.stdout}\n{result.stderr}"
    )
    return out_path.read_bytes()


def _published() -> dict:
    """The committed artefact's data, parsed out of the TypeScript.

    The file is one `export const REPORTS = <json> as const;` declaration, so the
    payload is sliced out and parsed as JSON rather than the TypeScript being
    executed -- the test must not depend on a JavaScript runtime.
    """
    text = TS_GENERATED.read_text(encoding="utf-8")
    marker = "export const REPORTS = "
    start = text.index(marker) + len(marker)
    end = text.rindex(" as const;")
    return json.loads(text[start:end])


def _source(name: str) -> dict:
    return json.loads((REPORTS_DIR / name).read_text(encoding="utf-8"))


def _resolve(document, pointer: str):
    """The value at a ``/``-separated pointer. The test's own resolver, so a bug
    in the generator's cannot hide behind itself."""
    here = document
    for step in pointer.split("/"):
        if isinstance(here, list):
            here = here[int(step)]
        else:
            here = here[step]
    return here


def _scalars(value, out: list | None = None) -> list:
    """Every scalar in a nested structure, in traversal order."""
    out = [] if out is None else out
    if isinstance(value, dict):
        for item in value.values():
            _scalars(item, out)
    elif isinstance(value, list):
        for item in value:
            _scalars(item, out)
    else:
        out.append(value)
    return out


# --- The load-bearing byte comparison, and both of its directions -------------


def test_generated_reports_are_byte_identical_to_a_fresh_bake(tmp_path):
    fresh = _bake_or_fail(tmp_path / "reports.ts")
    committed = TS_GENERATED.read_bytes()
    assert fresh == committed, (
        f"{TS_GENERATED.relative_to(ROOT)} is out of sync with reports/. Never "
        f"edit it by hand -- run:\n"
        f"    PYTHONPATH=src .venv/bin/python scripts/build_site_data.py"
    )


def test_editing_a_report_moves_the_bake(tmp_path):
    """Direction one, mechanically: a changed measurement changes the artefact.

    Without this the byte comparison above could be passing over a generator that
    ignores its inputs -- and a generator that ignored its inputs would keep
    passing it forever.
    """
    reports = tmp_path / "reports"
    shutil.copytree(REPORTS_DIR, reports, ignore=shutil.ignore_patterns("figures"))
    document = json.loads((reports / "counting_accuracy.json").read_text())
    before = document["methods"]["engine+gate"]["full"]["f1"]
    document["methods"]["engine+gate"]["full"]["f1"] = before + 0.01
    (reports / "counting_accuracy.json").write_text(json.dumps(document))

    result = _bake(tmp_path / "moved.ts", reports=reports)
    assert result.returncode == 0, result.stderr
    assert (tmp_path / "moved.ts").read_bytes() != TS_GENERATED.read_bytes(), (
        "a changed F1 in the source report did not change the baked artefact, so "
        "the byte comparison is not actually watching the reports"
    )


def test_editing_the_artefact_breaks_the_comparison(tmp_path):
    """Direction two: a hand-edited artefact no longer matches a fresh bake."""
    tampered = TS_GENERATED.read_bytes().replace(b"0.9142857142857143", b"0.9999", 1)
    assert tampered != TS_GENERATED.read_bytes(), (
        "the engine's committed F1 is not in the artefact, so this control is "
        "not exercising anything"
    )
    assert tampered != _bake_or_fail(tmp_path / "reports.ts")


def test_the_bake_is_deterministic_across_runs(tmp_path):
    """Same inputs, same bytes -- otherwise `docs/` could not be reproduced."""
    assert _bake_or_fail(tmp_path / "first.ts") == _bake_or_fail(tmp_path / "second.ts")


def test_the_artefact_carries_the_do_not_edit_header():
    assert TS_GENERATED.read_text(encoding="utf-8").splitlines()[0] == HEADER


# --- Completeness: what byte equality cannot see ------------------------------


def test_every_report_file_is_published():
    """A benchmark that is not declared would never reach the site, and the
    artefact would regenerate byte-identically without it."""
    on_disk = {path.name for path in REPORTS_DIR.glob("*.json")}
    published = {
        section["source"].removeprefix("reports/")
        for key, section in _published().items()
        if key != "model"
    }
    assert published == on_disk, (
        "reports/ and the baked sections disagree; every report file must be "
        "declared in scripts/build_site_data.py"
    )


def test_the_artefact_is_not_vacuously_small():
    published = _published()
    assert len(published) >= MINIMUM_SECTIONS, sorted(published)
    scalars = _scalars(published)
    assert len(scalars) >= MINIMUM_PUBLISHED_SCALARS, (
        f"only {len(scalars)} published values; expected at least "
        f"{MINIMUM_PUBLISHED_SCALARS}. Two empty structures compare equal, so "
        f"without this floor an emptied spec passes every test here."
    )


#: Pointers that MUST be published, written here rather than read from the
#: generator. Each one is a figure some claim on the page rests on, so losing it
#: from the spec has to fail even though the artefact would still round-trip.
#: The pairs are (path in the baked object, pointer into the source report).
COVERAGE = [
    # Counting: the headline accuracy row, and the two rules it is measured against.
    ("counting/methods", "methods", "engine+gate", "full", "precision"),
    ("counting/methods", "methods", "engine+gate", "full", "recall"),
    ("counting/methods", "methods", "engine+gate", "full", "f1"),
    # The strict adjudication, now a stat tile of its own rather than a row in a
    # disclosure, which is why it came off UNRENDERED below.
    ("counting/methods", "methods", "engine+gate", "certain_only", "f1"),
    ("counting/methods", "methods", "centroid+gate", "full", "f1"),
    ("counting/methods", "methods", "greedy-iou+gate", "full", "f1"),
    ("counting/methods", "methods", "engine+band", "full", "true_positives"),
    ("counting/methods", "methods", "engine+per-frame", "full", "count_error"),
    ("counting/labels/total", "labels", "total"),
    ("counting/timing", "timing", "engine+gate", "ms_per_frame"),
    # Robustness: the 2 fps collapse, the jitter collapse, the dropout series.
    ("robustness/protocols", "protocols", "frame_rate", "entries", 5, "methods", "engine+gate", "f1"),
    ("robustness/protocols", "protocols", "box_jitter", "entries", 2, "methods", "engine+gate", "f1"),
    ("robustness/protocols", "protocols", "detection_dropout", "entries", 4, "methods", "engine+gate", "f1"),
    ("robustness/associationFloor/largestGain/gain", "association_floor_ablation", "largest_f1_gain", "gain"),
    ("robustness/associationFloor/doesNotExplain", "association_floor_ablation", "protocols_the_floor_does_not_explain"),
    ("robustness/trackerSeparation/engineLeadsAnyDegradedLevel", "questions", "tracker_separation", "engine_leads_at_any_degraded_level"),
    ("robustness/trackerSeparation/engineLowestOnEveryIdentityLevel", "questions", "tracker_separation", "engine_lowest_on_every_identity_level"),
    ("robustness/jitter/stressAtMaxSigma/lowest", "jitter_calibration", "stress_multiple_at_max_sigma", "lowest"),
    # Tracking, including the claims it refuses to make.
    ("tracking/clean/trackers", "clean", "trackers", "engine", "fragmentation_ratio"),
    ("tracking/claimsNotMade", "claims_not_made", 0, "claim"),
    ("tracking/gateRegion/halfWidthPx", "gate_region", "half_width_px"),
    # Speed, tier 1: the only absolute speed claim the product makes.
    ("speedSynthetic/roadPlane/holdoutMaxErrorM", "road_plane", "holdout_max_error_m"),
    ("speedSynthetic/fullChain/settled/rmseKmh", "zero_noise", "full_chain", "settled", "rmse_kmh"),
    ("speedSynthetic/checkC/maxAbsDifferenceKmh", "check_c", "max_abs_difference_kmh"),
    # Speed, tier 2: the negative result and its controls.
    ("speedReal/absoluteSpeedPublished", "absolute_speed_published"),
    ("speedReal/bracket/lowerM", "honest_bracket_on_the_along_road_scale", "lower_m"),
    ("speedReal/guardrailControls/bands", "anchor_candidates", 0, "matched_controls", 0, "spread_percent"),
    ("speedReal/dividerDisagreement/ratioRange", "divider_disagreement", "ratio_range"),
    ("speedReal/cleanMeasurement/robustWeightedRmsPx", "the_one_clean_measurement", "robust_weighted_residual_rms_px"),
    # The detector-noise proxy the jitter sweep is calibrated against.
    ("detectionNoise/residuals/centreY/stdPx", "residuals", "centre_y", "std_px"),
    # Cross-surface parity.
    ("parity/caseCount", "caseCount"),
    ("parity/speedToleranceKmh", "speedToleranceKmh"),
]

SECTION_FILES = {
    "counting": "counting_accuracy.json",
    "robustness": "robustness.json",
    "tracking": "tracking.json",
    "speedSynthetic": "speed_synthetic.json",
    "speedReal": "speed_real.json",
    "detectionNoise": "detection_noise.json",
    "parity": "parity.json",
}


@pytest.mark.parametrize("entry", COVERAGE, ids=lambda entry: entry[0] + "|" + str(entry[-1]))
def test_every_load_bearing_figure_is_published_with_its_measured_value(entry):
    """A figure named here must be reachable in the artefact and equal to the
    source. This is the half that a subset cannot satisfy."""
    where, *pointer = entry
    section_key = where.split("/")[0]
    source_value = _resolve(_source(SECTION_FILES[section_key]), "/".join(str(p) for p in pointer))

    published = _resolve(_published(), where)
    found = _find_value(published, source_value)
    assert found, (
        f"{where} does not carry {source_value!r} from "
        f"{SECTION_FILES[section_key]}:{'/'.join(str(p) for p in pointer)}"
    )


def _find_value(haystack, needle) -> bool:
    """Whether ``needle`` occurs anywhere inside ``haystack``.

    The coverage table names the group a figure lands in rather than its exact
    baked key, because the baked shape is the generator's business and renaming a
    key must not be a test failure -- losing the measurement must be.
    """
    if isinstance(haystack, dict):
        return any(_find_value(item, needle) for item in haystack.values())
    if isinstance(haystack, list):
        if haystack == needle:
            return True
        return any(_find_value(item, needle) for item in haystack)
    if isinstance(haystack, float) and isinstance(needle, float):
        return haystack == needle
    return type(haystack) is type(needle) and haystack == needle


#: The values the bake computes rather than copies, with their formulae written
#: out a second time here. A derived figure is still a figure on the page.
def test_every_derived_value_recomputes_from_the_source_reports():
    published = _published()
    counting = _source("counting_accuracy.json")
    robustness = _source("robustness.json")

    labels = counting["labels"]["total"]
    engine = counting["methods"]["engine+gate"]["full"]

    def f1(tp, predicted, truth):
        return 2.0 * tp / (predicted + truth)

    expected_f1_step = abs(
        f1(engine["true_positives"], engine["n_predicted"], labels)
        - f1(engine["true_positives"], engine["n_predicted"] - 1, labels)
    )
    assert published["counting"]["resolution"]["oneEventF1"] == expected_f1_step
    assert published["counting"]["resolution"]["oneEventPrecision"] == 1.0 / labels

    expected_cpu = (
        counting["timing"]["engine+gate"]["ms_per_frame"]
        / counting["timing"]["centroid+gate"]["ms_per_frame"]
    )
    assert published["counting"]["engineCpuMultiple"] == expected_cpu

    stress = robustness["jitter_calibration"]["stress_multiple_at_max_sigma"]
    for end in ("lowest", "highest"):
        assert published["robustness"]["jitter"]["stressAtSigma2"][end] == (
            stress[end] * 2.0 / stress["sigma_px"]
        )

    card = MODEL_CARD.read_text(encoding="utf-8")
    sizes = [int(value.replace(" ", "")) for value in re.findall(r"\| (1?\d[\d ]{6,10}) B", card)]
    model = published["model"]
    assert model["bytesSaved"] == model["fileSizeBytes"]["float32"] - model["fileSizeBytes"]["int8"]
    assert model["fileSizeBytes"]["float32"] in sizes, sizes
    assert model["detectionsLostFraction"] == 1.0 - model["recallAgainstFloat32"]["int8"]


def test_every_published_number_occurs_in_its_own_source_report():
    """A figure cannot be invented, mistyped, or taken from the wrong report.

    The six derived values and each section's `source` string are the declared
    exceptions; everything else must be a value that literally appears in the
    report it claims to come from.
    """
    published = _published()
    derived = {
        ("counting", "resolution", "oneEventF1"),
        ("counting", "resolution", "oneEventPrecision"),
        ("counting", "engineCpuMultiple"),
        ("robustness", "jitter", "stressAtSigma2", "lowest"),
        ("robustness", "jitter", "stressAtSigma2", "highest"),
    }
    problems = []
    for key, file_name in SECTION_FILES.items():
        available = set()
        for value in _scalars(_source(file_name)):
            if isinstance(value, float) and not math.isfinite(value):
                continue
            available.add((type(value).__name__, value))
        for path, value in _walk(published[key], (key,)):
            if path in derived or path[-1] == "source":
                continue
            if isinstance(value, str) and value in {
                name for name in _method_names(_source(file_name))
            }:
                continue  # a dict key promoted into a row, e.g. "engine+gate"
            if (type(value).__name__, value) not in available:
                problems.append(f"{'/'.join(str(p) for p in path)} = {value!r}")
    assert problems == [], problems[:12]


# --- Baked keys nothing on the page reads -------------------------------------
#
# The one subset nothing else here can catch. `tsc --noEmit` cannot see an unused
# key, byte equality reproduces it happily, the containment sweep only says it came
# from the right report, and COVERAGE names figures a claim rests on -- which by
# definition these are not. So a key that nothing renders would be published,
# unread and unguarded, and a later task would find it and trust it.
#
# The rule adopted: no baked key may be referenced by nothing AND guarded by
# nothing. These are guarded here instead of trimmed, because trimming risks
# removing something a later task wants and pinning is the cheaper guarantee.
# Each entry pins the key's baked value to the report cell it came from, which is
# what COVERAGE does for the figures the page does print.

#: The TypeScript that renders the results half. A baked key counts as read if its
#: name appears in one of these.
RENDERING_SOURCES = (
    "web/src/ui/kit.ts",
    "web/src/ui/figures.ts",
    "web/src/ui/results.ts",
    "web/src/ui/results-speed.ts",
)

#: (baked key, exact path in the baked object, pointer into the source report).
#:
#: The path ends in the key itself, except where the key names a CONTAINER: there
#: the path reaches one scalar inside it, which is what proves the container
#: arrived with content. `bandStepOver` is the only one.
UNRENDERED = [
    ("agreesEverywhere", "tracking/agreement/agreesEverywhere", "questions/agreement_with_crossing_f1/agrees_everywhere"),
    ("bandStepOver", "robustness/bandStepOver/verdict", "questions/band_step_over/verdict"),
    ("baselineReport", "robustness/baselineReport", "baseline_report"),
    ("classConsistencySpread", "tracking/cleanDegeneracy/classConsistencySpread", "questions/clean_clip_degeneracy/class_consistency_spread"),
    ("controlIsOneUlpBelow", "parity/iouStraddle/controlIsOneUlpBelow", "iouStraddle/controlIsOneUlpBelow"),
    ("detectionsKept", "robustness/protocols/0/entries/1/detectionsKept", "protocols/frame_rate/entries/1/detections_kept"),
    ("detectionsTotal", "robustness/protocols/0/entries/1/detectionsTotal", "protocols/frame_rate/entries/1/detections_total"),
    ("discriminates", "tracking/cleanDegeneracy/discriminates", "questions/clean_clip_degeneracy/discriminates"),
    ("framePx", "speedSynthetic/camera/framePx", "camera/frame_px"),
    ("gatingDistance", "parity/iouStraddle/gatingDistance", "iouStraddle/gatingDistance"),
    ("groundTruth", "counting/groundTruth", "ground_truth"),
    ("howFitted", "speedSynthetic/roadPlane/howFitted", "road_plane/how_fitted"),
    ("labelNegative", "counting/gate/labelNegative", "gate/label_negative"),
    ("labelPositive", "counting/gate/labelPositive", "gate/label_positive"),
    ("loosestHelps", "robustness/associationFloor/loosestHelps", "association_floor_ablation/loosening_the_floor_helps"),
    ("maxGapFrames", "robustness/protocols/0/entries/5/maxGapFrames", "protocols/frame_rate/entries/5/max_gap_frames"),
    ("meanAbsErrorKmh", "speedSynthetic/homographyOnly/settled/meanAbsErrorKmh", "zero_noise/homography_chain_only/settled/mean_abs_error_kmh"),
    ("meanPeriodU", "speedReal/guardrailControls/bands/5/meanPeriodU", "anchor_candidates/0/matched_controls/5/mean_period_u"),
    ("methodsCompared", "robustness/trackerSeparation/methodsCompared", "questions/tracker_separation/methods_compared"),
    ("monotonic", "speedSynthetic/monotonic", "monotonic"),
    ("nGroundTruth", "counting/methods/0/nGroundTruth", "methods/engine+gate/full/n_ground_truth"),
    ("publishedHalfWidthPx", "tracking/gateRegionSweep/publishedHalfWidthPx", "gate_region_sweep/published_half_width_px"),
    ("recallCeiling", "robustness/protocols/0/entries/5/recallCeiling", "protocols/frame_rate/entries/5/resolution/reachability/recall_ceiling"),
    ("separateUndegraded", "robustness/trackerSeparation/separateUndegraded", "questions/tracker_separation/trackers_separate_on_undegraded_footage"),
    ("sourceReport", "robustness/jitter/sourceReport", "jitter_calibration/source_report"),
    ("startFrame", "parity/realClip/startFrame", "realClip/startFrame"),
    ("trackersCompared", "tracking/trackersCompared", "trackers_compared"),
]


def _baked_key_names() -> set:
    return {name for name in _method_names(_published()) if name != "source"}


def _rendering_text() -> str:
    return "".join((ROOT / path).read_text(encoding="utf-8") for path in RENDERING_SOURCES)


def test_no_baked_key_is_both_unread_and_unguarded():
    """Exact set equality, in both directions.

    A new baked key that nothing renders must be pinned here or removed -- it
    cannot simply appear. And a key that STARTS being rendered must come off this
    list, so the list cannot quietly accumulate keys that are now covered twice
    while a genuinely orphaned one hides among them.
    """
    text = _rendering_text()
    for path in RENDERING_SOURCES:
        assert (ROOT / path).exists(), f"{path} is missing; this guard must not pass by absence"
    unread = {
        name
        for name in _baked_key_names()
        if re.search(rf"\b{re.escape(name)}\b", text) is None
    }
    assert unread == {key for key, _baked, _source in UNRENDERED}, (
        "baked keys the page does not read changed. Add each new one to UNRENDERED "
        "with the report cell it comes from, or drop it from the spec; remove any "
        "that a section now renders."
    )


@pytest.mark.parametrize("entry", UNRENDERED, ids=lambda entry: entry[0])
def test_a_baked_key_the_page_does_not_read_still_matches_its_report(entry):
    key, baked_path, pointer = entry
    section = baked_path.split("/")[0]
    baked = _resolve(_published(), baked_path)
    source_value = _resolve(_source(SECTION_FILES[section]), pointer)
    assert type(baked) is type(source_value) and baked == source_value, (
        f"{baked_path} = {baked!r} but {SECTION_FILES[section]}:{pointer} = "
        f"{source_value!r}; key {key}"
    )


def _walk(value, path):
    if isinstance(value, dict):
        for key, item in value.items():
            yield from _walk(item, path + (key,))
    elif isinstance(value, list):
        for index, item in enumerate(value):
            yield from _walk(item, path + (index,))
    else:
        yield path, value


def _method_names(document, out: set | None = None) -> set:
    """Every dict key in a report, so a key promoted into a row is recognised."""
    out = set() if out is None else out
    if isinstance(document, dict):
        for key, item in document.items():
            out.add(key)
            _method_names(item, out)
    elif isinstance(document, list):
        for item in document:
            _method_names(item, out)
    return out


# --- The redaction: no absolute km/h from the flagship clip -------------------


def test_the_flagship_clip_speed_is_in_the_reports_but_not_on_the_page():
    """A discriminating pair. The must-not-publish half is the rule; the
    must-still-exist half is what proves the guard is live -- if the field were
    simply gone from reports/, this test would be passing over nothing."""
    parity = _source("parity.json")
    assert FORBIDDEN_SPEED_KEY in parity["realClip"], (
        "the redacted field is no longer in reports/parity.json, so the guard "
        "below is passing over nothing; re-derive the redaction"
    )
    forbidden = parity["realClip"][FORBIDDEN_SPEED_KEY]

    artefact = TS_GENERATED.read_text(encoding="utf-8")
    assert FORBIDDEN_SPEED_KEY not in artefact
    assert repr(forbidden) not in artefact
    # Also the digits alone: a reformatted literal would slip past an exact
    # repr match, and it is the FIGURE that is prohibited, not its spelling.
    assert f"{forbidden:.2f}"[:6] not in artefact


@pytest.mark.parametrize(
    "path",
    [
        "web/index.html",
        "web/src/ui/kit.ts",
        "web/src/ui/results.ts",
        "web/src/ui/results-speed.ts",
        "web/src/ui/figures.ts",
        "docs/index.html",
    ],
)
def test_no_authored_or_published_surface_carries_that_speed(path):
    """The prohibition is about the page, so it is asserted over the page --
    the authored markup, the modules that write the results sections, and the
    published entry point."""
    target = ROOT / path
    assert target.exists(), f"{path} is missing; the guard must not pass by absence"
    text = target.read_text(encoding="utf-8", errors="ignore")
    forbidden = _source("parity.json")["realClip"][FORBIDDEN_SPEED_KEY]
    assert FORBIDDEN_SPEED_KEY not in text
    assert f"{forbidden:.2f}"[:6] not in text


#: Every published surface that states the redaction in prose. ``docs/`` is the
#: bake of ``web/`` and both are served, so both are pinned.
REDACTION_PROSE = (
    "web/index.html",
    "docs/index.html",
    "web/public/CALIBRATION.md",
    "docs/CALIBRATION.md",
    "README.md",
)

#: An absence claim whose scope reaches ``reports/``. The two guards above
#: REQUIRE the figure to be in reports/parity.json -- the parity harness
#: reconstructs the withdrawn survey as an instrument for comparing two engines
#: against each other, not as a calibration, and the figure is the record of
#: that comparison. So a published sentence denying it there is contradicted by
#: this project's own data AND by its own guards, which is the one failure mode
#: this project cannot ship. The prohibition is on the page, the four documents
#: and the bake; it was never on the measurement record.
_ABSENCE_REACHING_THE_REPORTS = re.compile(
    r"\bno\b[^.]{0,80}?\bkm/h\b[^.]{0,200}?"
    r"(?:\b(?:or|nor|and) in (?:a|the|any) reports?\b|\bnot in (?:a|the|any) reports?\b)",
    re.IGNORECASE,
)


@pytest.mark.parametrize("path", REDACTION_PROSE)
def test_no_published_surface_denies_the_figure_the_reports_actually_hold(path):
    """The redaction must be stated as narrowly as it is enforced.

    A discriminating pair again, and deliberately the mirror of the one above:
    there the figure MUST be in reports/parity.json, so here no published
    sentence may say it is not. The prose and the guard have to be able to be
    true at the same time.
    """
    target = ROOT / path
    assert target.exists(), f"{path} is missing; the guard must not pass by absence"
    text = target.read_text(encoding="utf-8")

    # The half that proves this guard is live: the fact the prose must not deny.
    parity = _source("parity.json")
    assert FORBIDDEN_SPEED_KEY in parity["realClip"], (
        "the figure is no longer in reports/parity.json, so this guard is "
        "passing over nothing; re-derive the redaction"
    )

    overreach = _ABSENCE_REACHING_THE_REPORTS.search(text)
    assert overreach is None, (
        f"{path} claims no km/h figure from the flagship clip is in the "
        f"reports, but reports/parity.json carries realClip.{FORBIDDEN_SPEED_KEY} "
        f"and the guards require it to: {overreach.group(0)!r}"
    )


def test_the_overreach_detector_fires_on_the_sentence_that_motivated_it():
    """Otherwise the guard above is a regex that matches nothing, for ever."""
    withdrawn = (
        "the engine returns nothing for speed on that clip, and no km/h figure "
        "derived from it appears anywhere on this page or in the reports behind it."
    )
    assert _ABSENCE_REACHING_THE_REPORTS.search(withdrawn) is not None
    also_withdrawn = (
        "no absolute km/h figure from that clip appears anywhere in this "
        "project — not in the README, not on the site, not in a report."
    )
    assert _ABSENCE_REACHING_THE_REPORTS.search(also_withdrawn) is not None
    # And the must-survive control: the narrow claim, which is what the page
    # says now, and the README's framing of where the figure legitimately is.
    assert _ABSENCE_REACHING_THE_REPORTS.search(
        "no km/h figure derived from it appears anywhere on this page — the "
        "parity record carries one, from a matrix reconstructed there to hand "
        "two engines the same plane: an instrument, not a calibration."
    ) is None
    assert _ABSENCE_REACHING_THE_REPORTS.search(
        "It is an instrument, not a calibration, and no km/h figure about this "
        "clip is reported anywhere."
    ) is None


def test_a_redaction_whose_field_has_gone_refuses_the_bake(tmp_path):
    """A stale redaction must fail loudly rather than protect nothing."""
    reports = tmp_path / "reports"
    shutil.copytree(REPORTS_DIR, reports, ignore=shutil.ignore_patterns("figures"))
    parity = json.loads((reports / "parity.json").read_text())
    del parity["realClip"][FORBIDDEN_SPEED_KEY]
    (reports / "parity.json").write_text(json.dumps(parity))

    result = _bake(tmp_path / "out.ts", reports=reports)
    assert result.returncode != 0
    assert FORBIDDEN_SPEED_KEY in result.stderr
    assert not (tmp_path / "out.ts").exists()


# --- Refusals: the contract, exercised ---------------------------------------


def _reports_copy(tmp_path: Path) -> Path:
    reports = tmp_path / "reports"
    shutil.copytree(REPORTS_DIR, reports, ignore=shutil.ignore_patterns("figures"))
    return reports


def test_a_report_file_that_is_not_declared_refuses_the_bake(tmp_path):
    """A new benchmark must reach the site or stop the build -- never be ignored."""
    reports = _reports_copy(tmp_path)
    (reports / "brand_new.json").write_text('{"schema": 1}')
    result = _bake(tmp_path / "out.ts", reports=reports)
    assert result.returncode != 0
    assert "brand_new.json" in result.stderr
    assert not (tmp_path / "out.ts").exists()


def test_a_declared_report_that_has_gone_refuses_the_bake(tmp_path):
    reports = _reports_copy(tmp_path)
    (reports / "tracking.json").unlink()
    result = _bake(tmp_path / "out.ts", reports=reports)
    assert result.returncode != 0
    assert "tracking.json" in result.stderr


def test_a_published_key_that_has_gone_refuses_the_bake(tmp_path):
    """The alternative -- emitting null and carrying on -- is how a projection
    becomes a subset nobody notices."""
    reports = _reports_copy(tmp_path)
    document = json.loads((reports / "counting_accuracy.json").read_text())
    del document["labels"]["total"]
    (reports / "counting_accuracy.json").write_text(json.dumps(document))

    result = _bake(tmp_path / "out.ts", reports=reports)
    assert result.returncode != 0
    assert "labels/total" in result.stderr
    assert not (tmp_path / "out.ts").exists()


def test_a_non_finite_figure_refuses_the_bake(tmp_path):
    """`NaN` and `Infinity` are not TypeScript literals, so the artefact would
    not compile -- and a page cannot print a figure that is not a number."""
    reports = _reports_copy(tmp_path)
    text = (reports / "counting_accuracy.json").read_text()
    document = json.loads(text)
    document["fps"] = float("nan")
    (reports / "counting_accuracy.json").write_text(
        json.dumps(document).replace('"fps": NaN', '"fps": NaN')
    )
    result = _bake(tmp_path / "out.ts", reports=reports)
    assert result.returncode != 0
    assert "not finite" in result.stderr


def test_a_model_card_without_its_comparison_table_refuses_the_bake(tmp_path):
    """The int8 refusal is a published negative, so its figures must be found."""
    card = tmp_path / "MODEL_CARD.md"
    card.write_text(
        MODEL_CARD.read_text(encoding="utf-8").replace("| File size |", "| Size |"),
        encoding="utf-8",
    )
    result = _bake(tmp_path / "out.ts", card=card)
    assert result.returncode != 0
    assert "File size" in result.stderr


@pytest.mark.parametrize(
    ("row", "column"),
    [
        ("File size", 1),
        ("File size", 2),
        ("Detections over 40 frames", 1),
        ("Detections over 40 frames", 2),
        ("Recall against float32", 2),
        ("Mean IoU of matched boxes", 2),
    ],
)
def test_a_model_card_cell_emptied_with_an_em_dash_refuses_the_bake(tmp_path, row, column):
    """EVERY declared cell, not only the ones the derived figures are computed from.

    This is the condition the model card was accepted as a second data source on:
    the parse fails loudly. It did not, for three of the five figures -- a card
    with an em-dashed ``Detections over 40 frames`` int8 cell exited 0 and baked
    ``model.detections.int8 = null``, and the architecture table then printed that
    null into a published comparison. A silent fallback here turns the ruling into
    a hole, so the refusal is asserted cell by cell.
    """
    text = MODEL_CARD.read_text(encoding="utf-8")
    for line in text.splitlines():
        if line.startswith(f"| {row} |"):
            parts = line.split("|")
            assert parts[column + 1].strip() not in {"", "—"}, (
                f"the {row!r} row already leaves column {column} empty, so this "
                f"mutation is not removing anything"
            )
            parts[column + 1] = " — "
            emptied = text.replace(line, "|".join(parts))
            break
    else:  # pragma: no cover - the row labels are asserted above
        pytest.fail(f"the card has no row labelled {row!r}")

    assert emptied != text, "the card was not modified, so nothing is being tested"
    card = tmp_path / "MODEL_CARD.md"
    card.write_text(emptied, encoding="utf-8")
    result = _bake(tmp_path / "out.ts", card=card)
    assert result.returncode != 0, result.stdout
    assert row in result.stderr


def test_the_committed_model_card_bakes_with_every_declared_cell_filled(tmp_path):
    """The control on the parametrised refusal above, varying a different axis:
    the same declared cells, unmodified. Without it, a generator that refused
    every card would satisfy all six mutations."""
    result = _bake(tmp_path / "out.ts")
    assert result.returncode == 0, result.stderr
    model = _published()["model"]
    for key in ("fileSizeBytes", "detections"):
        assert model[key]["float32"] is not None and model[key]["int8"] is not None
    for key in ("recallAgainstFloat32", "meanIouOfMatched"):
        assert model[key]["int8"] is not None


def test_a_model_card_without_a_stated_protocol_refuses_the_bake(tmp_path):
    """Every number on the page carries its protocol; the int8 table is no
    exception, and the generator will not publish it without one."""
    text = MODEL_CARD.read_text(encoding="utf-8")
    stripped = re.sub(
        r"40 frames sampled every 15th.*?IoU 0\.5", "measured somehow", text, flags=re.S
    )
    assert stripped != text, "the protocol sentence was not found to remove"
    card = tmp_path / "MODEL_CARD.md"
    card.write_text(stripped, encoding="utf-8")
    result = _bake(tmp_path / "out.ts", card=card)
    assert result.returncode != 0
    assert "protocol" in result.stderr
