"""The generated TypeScript constants must be exactly what the exporter
produces from the Python source, byte for byte.

Task 21 asserts the Python and TypeScript engines make identical crossing
decisions, produce identical track IDs and agree on speeds to 1e-6. That
assertion is only worth something if the two engines are reading the same
numbers. So the TypeScript side is never written by hand: it is generated,
and this file fails the moment the committed artefact and the Python source
disagree -- whichever side moved.
"""

import ast
import json
import math
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXPORTER = ROOT / "scripts" / "export_constants.py"
PY_SOURCE = ROOT / "src" / "trafficlens" / "core" / "constants.py"
TS_GENERATED = ROOT / "web" / "src" / "generated" / "constants.ts"

HEADER = "// generated by scripts/export_constants.py — do not edit"

#: `export const NAME = VALUE;` -- the only declaration form the exporter is
#: allowed to emit (notes section 2: no type layer beyond what the values need).
_TS_CONST = re.compile(r"^export const ([A-Z][A-Z0-9_]*) = (.+);$")


def _run_exporter(*args: str) -> subprocess.CompletedProcess:
    """Drive the exporter exactly the way a developer does: as a script."""
    return subprocess.run(
        [sys.executable, str(EXPORTER), *args],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )


def _regenerate(out_path: Path) -> bytes:
    result = _run_exporter("--out", str(out_path))
    assert result.returncode == 0, (
        f"the exporter failed on the committed constants source:\n"
        f"{result.stdout}\n{result.stderr}"
    )
    return out_path.read_bytes()


def _python_constants() -> list[tuple[str, object]]:
    """Every module-level literal in constants.py, parsed independently of
    the exporter so a hand-picked subset cannot pass unnoticed."""
    module = ast.parse(PY_SOURCE.read_text(encoding="utf-8"))
    found = []
    for node in module.body:
        if isinstance(node, ast.Assign) and isinstance(node.value, ast.Constant):
            (target,) = node.targets
            found.append((target.id, node.value.value))
    return found


def _typescript_constants() -> list[tuple[str, str]]:
    """Every `export const` in the committed artefact, in file order."""
    text = TS_GENERATED.read_text(encoding="utf-8")
    return [
        (match.group(1), match.group(2))
        for match in (_TS_CONST.match(line) for line in text.splitlines())
        if match
    ]


# --- The load-bearing test ----------------------------------------------------


def test_generated_constants_are_byte_identical_to_a_fresh_export(tmp_path):
    """Regenerate into a temp file and compare bytes with the committed file.

    Fails in BOTH directions by construction: edit the committed TypeScript
    and the fresh export no longer matches it; edit the Python source without
    regenerating and the fresh export no longer matches the committed file.
    """
    fresh = _regenerate(tmp_path / "constants.ts")
    committed = TS_GENERATED.read_bytes()
    assert fresh == committed, (
        f"{TS_GENERATED.relative_to(ROOT)} is out of sync with "
        f"{PY_SOURCE.relative_to(ROOT)}. Never edit the TypeScript by hand -- run:\n"
        f"    .venv/bin/python scripts/export_constants.py"
    )


# --- Properties the byte comparison alone does not pin down -------------------


def test_export_is_deterministic_across_runs(tmp_path):
    """Same input, same bytes, every run -- otherwise the test above would be
    a coin flip and Task 24's reproducible build would be impossible."""
    first = _regenerate(tmp_path / "first.ts")
    second = _regenerate(tmp_path / "second.ts")
    assert first == second


def test_generated_file_carries_the_do_not_edit_header():
    first_line = TS_GENERATED.read_text(encoding="utf-8").splitlines()[0]
    assert first_line == HEADER


def test_every_python_constant_is_exported_with_its_exact_value():
    """Independent of the exporter: parse both sides and compare.

    Byte equality alone would happily accept an exporter that emits a subset,
    because the regenerated file would carry that same subset. This does not.
    """
    python = _python_constants()
    typescript = _typescript_constants()

    assert [name for name, _ in typescript] == [name for name, _ in python], (
        "the TypeScript constants do not match the Python ones, name for name "
        "and in source order"
    )

    for (name, py_value), (_, ts_literal) in zip(python, typescript):
        if isinstance(py_value, bool):
            assert ts_literal == ("true" if py_value else "false"), name
        elif isinstance(py_value, str):
            assert json.loads(ts_literal) == py_value, name
        else:
            # Both sides are IEEE-754 doubles, and the exported literal is the
            # shortest string that round-trips, so this is exact -- no epsilon.
            assert float(ts_literal) == float(py_value), name


def test_constants_source_holds_only_upper_case_literal_assignments():
    """The invariant the exporter is allowed to assume (controller notes, 0).

    If this fails, the fix is to move the computation to its point of use --
    not to teach the exporter to evaluate Python.
    """
    module = ast.parse(PY_SOURCE.read_text(encoding="utf-8"))
    offenders = []
    for index, node in enumerate(module.body):
        if index == 0 and isinstance(node, ast.Expr):
            if isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
                continue  # the module docstring
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            offenders.append((node.lineno, ast.dump(node)[:80]))
            continue
        (target,) = node.targets
        if not isinstance(target, ast.Name) or target.id != target.id.upper():
            offenders.append((node.lineno, ast.dump(node)[:80]))
        elif not isinstance(node.value, ast.Constant):
            offenders.append((node.lineno, f"{target.id} is not a plain literal"))
        elif isinstance(node.value.value, float) and not math.isfinite(node.value.value):
            offenders.append((node.lineno, f"{target.id} is not finite"))
    assert offenders == [], offenders


def test_exporter_refuses_a_source_it_cannot_parse_as_literals(tmp_path):
    """A non-literal must stop the export, not be silently dropped.

    Silent skipping is the failure this whole mechanism exists to prevent: a
    constant missing from TypeScript would still regenerate byte-identically.
    """
    bad_source = tmp_path / "constants.py"
    bad_source.write_text("A_LITERAL = 1.5\nA_COMPUTED = 1.0 / 3.0\n", encoding="utf-8")
    out = tmp_path / "out.ts"

    result = _run_exporter("--source", str(bad_source), "--out", str(out))

    assert result.returncode != 0, "the exporter accepted a computed constant"
    assert "A_COMPUTED" in result.stderr
    assert not out.exists(), "the exporter wrote output despite refusing the source"
