#!/usr/bin/env python3
"""Validate speed in two tiers, and write both reports.

Tier 1 -- exact synthetic truth. A simulator places vehicles on a KNOWN
ground plane, moves them at EXACT known speeds, projects them through a
known pinhole camera, and emits detections perturbed by box noise whose
sigma is taken from ``reports/detection_noise.json``. The full tracker ->
homography -> speed chain runs on those detections. Where the plane is
known the scale is known, so absolute km/h error is meaningful -- this is
the only absolute speed claim this product makes.

Tier 2 -- real footage. It publishes a NEGATIVE result, with its
measurements: the flagship clip has no independent along-road anchor, so no
absolute km/h from it is trustworthy, and ``configs/motorway.yaml`` ships
with no calibration block. Everything Tier 2 asserts is recomputed here
from the committed survey fixture, not copied from prose.

Writes into the tracked ``reports/`` directory:

1. ``reports/speed_synthetic.json``
2. ``reports/speed_real.json``
3. ``reports/figures/speed_*.png`` (with ``--figures``)

Usage:

    PYTHONPATH=src .venv/bin/python scripts/bench_speed.py --figures

Nothing here needs the clip, the weights, or a GPU: Tier 1 is generated and
Tier 2 runs off ``data/fixtures/motorway_scale_survey.json``.
"""

import argparse
import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

from trafficlens.bench.harness import write_report  # noqa: E402
from trafficlens.bench.scale import (  # noqa: E402
    along_road_transfer,
    divider_step_metres,
    fit_line,
    load_scale_survey,
    road_vanishing_point,
    robust_fit_line,
    surveyed_homography,
    surveyed_homography_vanishing_point,
    vanishing_point_spread,
)
from trafficlens.bench.simulate import (  # noqa: E402
    MEASURED_NOISE_STATISTICS,
    ScenePlane,
    SimulationError,
    noise_from_detection_report,
    score_scene,
    simulate_scene,
    time_of_flight_scores,
)
from trafficlens.core.constants import SPEED_WINDOW_S  # noqa: E402
from trafficlens.core.homography import CalibrationError, RoadPlane  # noqa: E402

#: The report's ``limitations`` field, verbatim. Tier 1 exercises the
#: tracking -> homography -> speed chain on GENERATED boxes; how a real
#: detector places a box is not measured here at all.
LIMITATIONS = (
    "This measures the tracking -> homography -> speed chain and NOT the "
    "detector. The boxes are generated from a known 3-D scene, not "
    "detected, so nothing here says anything about detection accuracy, "
    "recall, class confusion, or how a real detector places a box on a "
    "real vehicle. The box-noise sigma is taken from "
    "reports/detection_noise.json, which labels itself a PROXY for "
    "detector jitter and is not a measurement of the detector either. "
    "CALIBRATION ERROR IS EXCLUDED BY CONSTRUCTION as well: the road "
    "plane is fitted from correspondences generated by the same camera, "
    "and the true road-plane-to-image mapping IS a homography, so the fit "
    "recovers that camera to about 6e-6 m. That is deliberate -- it "
    "removes calibration error from the measurement so what remains is "
    "the chain under test -- but it means the figures here are an upper "
    "bound on field accuracy, not a prediction of it. A real deployment "
    "carries survey error on top, and it is usually the larger term."
)

#: Speed bands the report covers, km/h. Spans congested urban-motorway
#: crawl to the fast end of unrestricted autobahn traffic.
SPEED_BANDS = (30.0, 50.0, 70.0, 90.0, 110.0, 130.0)

#: Multiples of the measured per-component sigma vector the sweep visits.
#: 1.0 is the measured point itself and is marked as such on the figure.
NOISE_MULTIPLES = (0.0, 0.25, 0.5, 1.0, 2.0, 4.0)

#: Seeds averaged at each sweep point. Each seed is one whole scene, so
#: this is 8 independent realisations of every band at every sigma.
SEEDS = tuple(range(8))

#: Gates for Check C, in world metres along the road.
GATE_FAR_Y_M, GATE_NEAR_Y_M = 130.0, 40.0

#: Horizon rows every Tier-2 result is checked against, spanning well above
#: and below the vanishing-point row any fitted road-parallel line implies.
HORIZON_ROWS = (340.0, 356.0, 364.0, 372.468, 375.65, 380.0, 400.0)


def parse_args(argv=None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate speed in two tiers and write both reports."
    )
    parser.add_argument("--noise", default="reports/detection_noise.json")
    parser.add_argument("--synthetic-out", default="reports/speed_synthetic.json")
    parser.add_argument("--real-out", default="reports/speed_real.json")
    parser.add_argument("--figure-dir", default="reports/figures")
    parser.add_argument(
        "--figures",
        action="store_true",
        help="also write the PNGs (matplotlib is not a runtime dependency)",
    )
    return parser.parse_args(argv)


def resolve(path_like: str) -> Path:
    path = Path(path_like)
    return path if path.is_absolute() else ROOT / path


# --- statistics ---------------------------------------------------------------


def summarise(errors, truths) -> dict:
    """Absolute and relative error statistics for one group of samples."""
    n = len(errors)
    if n == 0:
        return {"n": 0}
    absolute = [abs(e) for e in errors]
    relative = [100.0 * abs(e) / t for e, t in zip(errors, truths)]
    return {
        "n": n,
        "mean_error_kmh": sum(errors) / n,
        "mean_abs_error_kmh": sum(absolute) / n,
        "max_abs_error_kmh": max(absolute),
        "rmse_kmh": math.sqrt(sum(e * e for e in errors) / n),
        "mean_relative_percent": sum(relative) / n,
        "max_relative_percent": max(relative),
    }


def rmse_by_band(samples) -> dict[float, float | None]:
    """Settled-sample RMSE per speed band, or None where a band produced
    no settled samples."""
    out: dict[float, float | None] = {}
    for speed in SPEED_BANDS:
        errors = [s.error_kmh for s in samples if s.truth_kmh == speed]
        out[speed] = (
            math.sqrt(sum(e * e for e in errors) / len(errors)) if errors else None
        )
    return out


def by_band(samples) -> list[dict]:
    rows = []
    for speed in SPEED_BANDS:
        group = [s for s in samples if s.truth_kmh == speed]
        row = {"speed_kmh": speed}
        row.update(
            summarise([s.error_kmh for s in group], [s.truth_kmh for s in group])
        )
        rows.append(row)
    return rows


# --- Tier 1 -------------------------------------------------------------------


def run_tier_1(noise_report: dict) -> dict:
    plane = ScenePlane()
    sigma_by_statistic = {
        statistic: noise_from_detection_report(noise_report, statistic)
        for statistic in MEASURED_NOISE_STATISTICS
    }
    # The sweep is anchored on the STD vector: it is the larger of the two
    # on the box centres, which is what the anchor -- and therefore the
    # speed -- is most sensitive to. The p95 vector is reported beside it
    # so a reader can place the typical case on the same curve.
    base = sigma_by_statistic["std_px"]

    def scene(seed, sigma, box_model="footprint"):
        return simulate_scene(
            plane,
            speeds_kmh=SPEED_BANDS,
            n_vehicles=len(SPEED_BANDS),
            fps=30.0,
            seed=seed,
            box_noise_px=sigma,
            box_model=box_model,
        )

    clean = scene(0, 0.0)
    tracked = score_scene(clean)
    bypassed = score_scene(clean, bypass_tracker=True)
    solid = score_scene(scene(0, 0.0, box_model="solid"))

    holdout_image, holdout_world = plane.holdout_points()
    holdout = plane.road_plane().reprojection_error(holdout_image, holdout_world)

    # What the Kalman smoothing actually buys, MEASURED rather than
    # assumed. The speed estimator is fed the tracker's smoothed anchor;
    # the alternative is the raw detection's own bottom-centre. At the
    # measured sigma, association does not fail (zero vehicles lost), so
    # this compares the two anchors and nothing else.
    smoothed_errors, raw_errors = [], []
    trade_off_lost = 0
    for seed in SEEDS:
        trade_scene = scene(seed, base)
        tracked_at_sigma = score_scene(trade_scene)
        raw_at_sigma = score_scene(trade_scene, bypass_tracker=True)
        trade_off_lost += len(tracked_at_sigma.lost_vehicles)
        smoothed_errors += list(tracked_at_sigma.settled_samples)
        raw_errors += list(raw_at_sigma.settled_samples)
    smoothed_rmse = rmse_by_band(smoothed_errors)
    raw_rmse = rmse_by_band(raw_errors)
    trade_off_rows = []
    for speed in SPEED_BANDS:
        smoothed, raw = smoothed_rmse[speed], raw_rmse[speed]
        trade_off_rows.append(
            {
                "speed_kmh": speed,
                "kalman_anchor_rmse_kmh": smoothed,
                "raw_detection_anchor_rmse_kmh": raw,
                "better": (
                    None
                    if smoothed is None or raw is None
                    else ("kalman_anchor" if smoothed < raw else "raw_detection_anchor")
                ),
            }
        )

    sweep = []
    for multiple in NOISE_MULTIPLES:
        sigma = tuple(multiple * s for s in base)
        samples, lost, scenes = [], 0, 0
        refused = None
        for seed in SEEDS:
            try:
                score = score_scene(scene(seed, sigma))
            except SimulationError as error:
                refused = str(error)
                break
            samples += list(score.settled_samples)
            lost += len(score.lost_vehicles)
            scenes += 1
        entry = {
            "sigma_multiple_of_measured_std": multiple,
            "sigma_px": {
                "centre_x": sigma[0],
                "centre_y": sigma[1],
                "box_width": sigma[2],
                "box_height": sigma[3],
            },
            "scenes": scenes,
            "vehicles_the_tracker_lost": lost,
            "vehicles_offered": scenes * len(SPEED_BANDS),
            "overall": summarise(
                [s.error_kmh for s in samples], [s.truth_kmh for s in samples]
            ),
            "by_band": by_band(samples),
        }
        if refused is not None:
            entry["refused"] = refused
        sweep.append(entry)

    rmses = [
        row["overall"]["rmse_kmh"] for row in sweep if row["overall"]["n"] > 0
    ]
    check_c = time_of_flight_scores(
        clean, gate_far_y_m=GATE_FAR_Y_M, gate_near_y_m=GATE_NEAR_Y_M
    )

    return {
        "schema": 1,
        "tier": 1,
        "what_this_is": (
            "Absolute speed accuracy where the ground truth is exact. The "
            "truth is an INPUT -- the caller's own list of speeds -- and is "
            "invariant under the seed, the noise level and the box model, "
            "i.e. under every knob that changes what the estimator is "
            "shown. Nothing the estimator produces feeds back into it."
        ),
        "limitations": LIMITATIONS,
        "camera": {
            "focal_px": plane.focal_px,
            "principal_point_px": [plane.principal_x, plane.principal_y],
            "height_m": plane.height_m,
            "pitch_deg": plane.pitch_deg,
            "frame_px": [plane.frame_width, plane.frame_height],
            "note": (
                "A camera on an overpass above a motorway, the deployment "
                "this product is built for. Vehicles are scored over world "
                "y = 30 to 140 m, the band in which the projected box "
                "spans about 66 px down to 15 px -- the near end matches "
                "the real clip's measured median box of 66.8 x 48.8 px."
            ),
        },
        "road_plane": {
            "how_fitted": (
                "RoadPlane.from_correspondences over six surveyed dash "
                "centroids on two divider lines 3.75 m apart, plus a "
                "two-point holdout -- the same SHAPE of survey a "
                "deployment does. Deliberately NOT the camera's analytic "
                "inverse."
            ),
            "holdout_max_error_m": holdout["max_m"],
            "holdout_mean_error_m": holdout["mean_m"],
        },
        "settled_definition": {
            "window_s": SPEED_WINDOW_S,
            "meaning": (
                "A sample is 'settled' once the track has been observed "
                "for a full speed window. Below that the estimator fits a "
                "slope over a partly-filled window while the Kalman "
                "filter's velocity is still converging from its "
                "zero-velocity initialisation. Both are reported; the "
                "headline figures are the settled ones."
            ),
        },
        "speed_bands_kmh": list(SPEED_BANDS),
        "noise_calibration": {
            "source": "reports/detection_noise.json",
            "source_caveat": (
                "That report labels itself a PROXY for detector box noise, "
                "and its distribution is heavy-tailed -- the std exceeds "
                "the p95 on both box centres, because a few large "
                "excursions dominate the variance. Read p95 for the "
                "typical case and std for the tail. Neither is a "
                "measurement of the detector."
            ),
            "sigma_px": {
                statistic: {
                    "centre_x": value[0],
                    "centre_y": value[1],
                    "box_width": value[2],
                    "box_height": value[3],
                }
                for statistic, value in sigma_by_statistic.items()
            },
            "sweep_anchored_on": "std_px",
            "why": (
                "The std vector is the larger of the two on the box "
                "centres, and the anchor -- hence the speed -- is most "
                "sensitive to centre noise. Multiple 1.0 on the sweep IS "
                "the measured point."
            ),
        },
        "zero_noise": {
            "homography_chain_only": {
                "what": (
                    "The simulator's noise-free detections fed straight to "
                    "SpeedEstimator, tracker bypassed. This is the "
                    "requirement's own chain: where the plane is known the "
                    "recovery must be exact."
                ),
                "requirement_kmh": 0.1,
                "settled": summarise(
                    [s.error_kmh for s in bypassed.settled_samples],
                    [s.truth_kmh for s in bypassed.settled_samples],
                ),
                "by_band": by_band(bypassed.settled_samples),
            },
            "full_chain": {
                "what": (
                    "The same detections through the full tracker -> "
                    "homography -> speed chain."
                ),
                "settled": summarise(
                    [s.error_kmh for s in tracked.settled_samples],
                    [s.truth_kmh for s in tracked.settled_samples],
                ),
                "all_samples_including_start_up": summarise(
                    [s.error_kmh for s in tracked.samples],
                    [s.truth_kmh for s in tracked.samples],
                ),
                "by_band": by_band(tracked.settled_samples),
                "finding": (
                    "The full chain does NOT meet the 0.1 km/h bar above "
                    "about 70 km/h, and the miss is attributable rather "
                    "than merely present. Three things identify it as the "
                    "constant-velocity Kalman filter lagging image-space "
                    "motion that accelerates as a vehicle approaches: the "
                    "settled residual is signed NEGATIVE at every band (a "
                    "lagging filter under-reads), it grows monotonically "
                    "with speed, and it vanishes to under 1e-4 km/h on the "
                    "identical detections with the tracker bypassed. The "
                    "tolerance was not widened to accommodate it; "
                    "tests/test_simulate.py asserts the mechanism. What "
                    "the lag buys is measured separately and is NOT a "
                    "uniform win -- see smoothing_trade_off below."
                ),
                "start_up_transient": (
                    "Before the window fills, the first reported speed "
                    "sits several km/h high and decays; SPEED_MIN_SAMPLES "
                    "lets a number out after 5 samples, which is 0.13 s of "
                    "data. Consumers wanting the accuracy figures above "
                    "should ignore a track's first "
                    f"{SPEED_WINDOW_S} s."
                ),
            },
            "smoothing_trade_off": {
                "what": (
                    "The speed estimator is fed the tracker's "
                    "Kalman-smoothed anchor. The alternative is the raw "
                    "detection's own bottom-centre. This is that "
                    "comparison, at the MEASURED sigma, over the same "
                    "scenes -- the question of what the lag is bought "
                    "with, answered by measurement rather than assumed."
                ),
                "sigma": "1x the measured std_px vector",
                "seeds": len(SEEDS),
                "vehicles_the_tracker_lost": trade_off_lost,
                "why_that_matters": (
                    "Zero lost vehicles means association is not a "
                    "variable here, so the two columns differ by the "
                    "anchor and nothing else."
                ),
                "by_band": trade_off_rows,
                "finding": (
                    "The trade is NOT uniform. Smoothing wins in the low "
                    "bands and LOSES in the high ones -- by up to about a "
                    "quarter, in exactly the bands whose zero-noise "
                    "residual misses the 0.1 km/h bar. So the lag is not "
                    "simply paid for by noise robustness at every speed. "
                    "The tracker is nonetheless left alone, for a "
                    "different and better reason: this is a synthetic "
                    "benchmark with generated boxes, exact truth and no "
                    "calibration error, and retuning a shipped tracker's "
                    "filter to it would be fitting the engine to the "
                    "measuring instrument. What the benchmark licenses is "
                    "reporting the effect, which is what it does."
                ),
            },
            "box_model_comparison": {
                "what": (
                    "'footprint' places the box's bottom-centre exactly on "
                    "the vehicle's projected ground point; 'solid' uses "
                    "the true bounding box of the projected 3-D vehicle, "
                    "so the anchor carries the geometric offset a real "
                    "detector's box would. The difference is reported "
                    "rather than hidden."
                ),
                "footprint_settled": summarise(
                    [s.error_kmh for s in tracked.settled_samples],
                    [s.truth_kmh for s in tracked.settled_samples],
                ),
                "solid_settled": summarise(
                    [s.error_kmh for s in solid.settled_samples],
                    [s.truth_kmh for s in solid.settled_samples],
                ),
                "why_it_barely_moves": (
                    "The offset between the box's bottom-centre and the "
                    "vehicle's ground reference point is very nearly "
                    "constant in world metres, and a constant offset does "
                    "not change a fitted slope."
                ),
            },
        },
        "noise_sweep": sweep,
        "monotonic": all(a < b for a, b in zip(rmses, rmses[1:])),
        "monotonic_note": (
            "RMSE rises at every step. The jump between 1x and 2x the "
            "measured sigma is not the speed chain degrading gracefully: "
            "it is ASSOCIATION starting to fail, visible in "
            "'vehicles_the_tracker_lost'. The sweep stops at 4x because by "
            "then 36 of 48 vehicles are already lost to association, so "
            "the surviving samples are a survivorship-biased sample of "
            "the easy tracks rather than a speed-accuracy measurement. "
            "The simulator does additionally refuse any scene whose boxes "
            "overlap -- an identity swap makes a measured speed "
            "meaningless -- but that refusal is not what ends this sweep, "
            "and it does not fire at any swept sigma: measured on this "
            "scene shape it first appears at about 8x, in 1 seed of 8."
        ),
        "check_c": {
            "what": (
                "Two gates a known ground distance apart give a "
                "time-of-flight speed per vehicle from two crossing "
                "instants and the surveyed separation. What makes it a "
                "cross-check is that it shares no PER-FRAME DISPLACEMENT "
                "with the homography estimate -- it never fits a slope, "
                "never differences successive positions, and never uses a "
                "window. It is not fully independent of the RoadPlane, "
                "and is not claimed to be: the crossing instants come "
                "from the same plane projecting the track's position, "
                "interpolated between the two frames that straddle each "
                "gate. Position, not displacement, is the shared part."
            ),
            "run_on": "the SIMULATED scene only",
            "why_not_on_real_footage": (
                "On the real clip the ground distance between two gates is "
                "itself known only through the along-road scale that has "
                "no independent anchor, so the check would be calibrated "
                "by the quantity it was meant to check. On the simulated "
                "scene both estimators share a KNOWN scale, so their "
                "agreement tests the two estimators against each other -- "
                "which is a real result, and the one Check C was wanted "
                "for."
            ),
            "gate_far_y_m": GATE_FAR_Y_M,
            "gate_near_y_m": GATE_NEAR_Y_M,
            "gate_separation_m": GATE_FAR_Y_M - GATE_NEAR_Y_M,
            "agreement_requirement_kmh": 1.0,
            "max_abs_difference_kmh": max(
                abs(r.difference_kmh) for r in check_c
            ),
            "per_vehicle": [
                {
                    "truth_kmh": r.truth_kmh,
                    "time_of_flight_kmh": r.time_of_flight_kmh,
                    "homography_kmh": r.homography_kmh,
                    "difference_kmh": r.difference_kmh,
                    "time_of_flight_error_kmh": r.time_of_flight_kmh - r.truth_kmh,
                }
                for r in check_c
            ],
        },
        "reproduce": (
            "PYTHONPATH=src .venv/bin/python scripts/bench_speed.py --figures"
        ),
    }


# --- Tier 2 -------------------------------------------------------------------


def run_tier_2(survey: dict) -> dict:
    divider_1 = survey["divider_lines"]["divider_1"]
    divider_2 = survey["divider_lines"]["divider_2"]

    steps = [
        divider_step_metres(survey, horizon_row=row) for row in HORIZON_ROWS
    ]
    reconciling = divider_step_metres(survey, horizon_row=463.0)

    rail_slope, rail_intercept, rail_rms = robust_fit_line(
        survey["guardrail_beam"]["points_px"]
    )
    _, _, rail_plain_rms, rail_plain_max = fit_line(
        survey["guardrail_beam"]["points_px"]
    )
    vp_x, vp_y = surveyed_homography_vanishing_point(survey)

    # The repair the obvious reading suggests, attempted and recorded.
    divider_1_image = [tuple(p) for p in divider_1["points_px"]]
    divider_1_world = [(0.0, y) for y in divider_1["assumed_world_y_m"]]
    try:
        RoadPlane.from_correspondences(divider_1_image, divider_1_world).validate()
        refit_outcome = "succeeded, which contradicts the recorded finding"
    except CalibrationError as error:
        refit_outcome = str(error)

    # The removed calibration's own residuals, for the record.
    plane = surveyed_homography(survey)
    holdout_indices = [2, 5]  # the 36 m and 90 m divider-1 dashes
    self_fit = plane.reprojection_error(
        [tuple(divider_1["points_px"][i]) for i in [0, 1, 3, 4]]
        + [tuple(p) for p in divider_2["points_px"]],
        [(0.0, divider_1["assumed_world_y_m"][i]) for i in [0, 1, 3, 4]]
        + [
            (divider_2["assumed_cross_road_offset_m"], y)
            for y in divider_2["assumed_world_y_m"]
        ],
    )
    holdout = plane.reprojection_error(
        [tuple(divider_1["points_px"][i]) for i in holdout_indices],
        [(0.0, divider_1["assumed_world_y_m"][i]) for i in holdout_indices],
    )

    road_vp = road_vanishing_point(survey)
    uniformity = {}
    for name in ("divider_1", "divider_2"):
        points = survey["divider_lines"][name]["points_px"]
        u = [1.0 / (road_vp[0] - x) for x, _ in points]
        deltas = [b - a for a, b in zip(u, u[1:])]
        mean = sum(deltas) / len(deltas)
        variance = sum((d - mean) ** 2 for d in deltas) / len(deltas)
        uniformity[name] = {
            "delta_u": deltas,
            "mean_delta_u": mean,
            "spread_percent": 100.0 * math.sqrt(variance) / mean,
        }

    return {
        "schema": 1,
        "tier": 2,
        "clip": "motorway-a40.webm",
        "headline": (
            "No usable independent along-road anchor exists in this clip, "
            "and the calibration that used to ship with it was internally "
            "inconsistent as well. Absolute km/h is not published from this "
            "footage, on any surface. configs/motorway.yaml ships with no "
            "calibration block, so the engine returns None for every speed "
            "on it -- the behaviour the engine's own policy was built to "
            "guarantee."
        ),
        "absolute_speed_published": False,
        "shipped_config_calibrated": False,
        "limitations": LIMITATIONS,
        "what_this_replaces": (
            "The plan's Tier 2 was to calibrate from German motorway "
            "lane-divider geometry (6 m stroke, 18 m period) and validate "
            "it three ways. Every part of that is unavailable. The 6 m + "
            "18 m justification is falsified by the clip's own paint: "
            "measured in a perspective-free coordinate the stroke is about "
            "0.50 of the period where that standard requires 0.333, and "
            "the three innocent explanations -- drift smear, resolution "
            "smearing at distance, mixed marking types -- were each tested "
            "and each fails. A reprojection residual on unused markings "
            "tests fit consistency, not absolute scale. A vehicle-footprint "
            "check measures the CROSS-road axis, and a homography admits an "
            "independent scale per world axis, so it cannot corroborate the "
            "along-road period at all. And two gates a known distance apart "
            "cannot give absolute km/h here because that distance is itself "
            "known only through the scale in dispute."
        ),
        "anchor_candidates": [
            {
                "candidate": "Guardrail (Schutzplanke) posts",
                "verdict": "PRESENT BUT NOT MEASURABLE",
                "what_was_measured": (
                    "Band-limited local period in the perspective-free "
                    "coordinate u = 1 / (vp_x - x), over four windows "
                    "across image x = 5 to 420, against matched controls "
                    "processed identically."
                ),
                "matched_controls": [
                    {
                        "band": "guardrail post band",
                        "mean_period_u": 3.72e-5,
                        "spread_percent": 9.1,
                    },
                    {
                        "band": "asphalt control A",
                        "mean_period_u": 3.01e-5,
                        "spread_percent": 31.8,
                    },
                    {
                        "band": "asphalt control B",
                        "mean_period_u": 3.30e-5,
                        "spread_percent": 22.8,
                    },
                    {
                        "band": "shoulder control",
                        "mean_period_u": 3.05e-5,
                        "spread_percent": 14.6,
                    },
                    {
                        "band": "behind-rail control",
                        "mean_period_u": 3.32e-5,
                        "spread_percent": 14.2,
                    },
                    {
                        "band": "positive control: divider-1 dashes",
                        "mean_period_u": 3.639e-4,
                        "spread_percent": 1.3,
                    },
                ],
                "why_the_controls_matter": (
                    "They are what make 'not measurable' a measurement "
                    "rather than a shrug. The post band is statistically "
                    "indistinguishable from featureless asphalt, its peaks "
                    "repeatedly land on the search-band edge (the "
                    "signature of broadband noise rather than a line), and "
                    "a full-span comb correlation scores the asphalt "
                    "control HIGHER than the posts. Meanwhile the positive "
                    "control recovers the known dash period to 1.3 %, so "
                    "the method demonstrably works where a periodicity "
                    "exists."
                ),
            },
            {
                "candidate": "Delineator posts (Leitpfosten)",
                "verdict": "PRESENT AND MEASURABLE BUT UNUSABLE",
                "what_was_measured": (
                    "Four posts on the right verge, transferred with the "
                    "along-road identity: 68 to 82 m per interval, mean "
                    "about 74 m, across every plausible horizon row."
                ),
                "why_unusable": (
                    "74 m matches no German Leitpfosten spacing (50 m "
                    "straight, 25 m in curves). The three intervals rise "
                    "monotonically by 15 %, which is not scatter; the "
                    "section visibly curves and the two far posts sit in "
                    "the bend, so the standard being compared against is "
                    "not even fixed; camera roll of up to 1.97 degrees "
                    "moves this particular transfer by up to 17 %; and "
                    "plus or minus 2 px on the far posts is 10 % on the "
                    "outermost interval alone. It is evidence AGAINST the "
                    "18 m assumption, not evidence FOR any alternative."
                ),
            },
            {
                "candidate": "Median barrier segment joints",
                "verdict": "ABSENT",
                "what_was_measured": (
                    "The median at 3x and 6x: a raised earth and gravel "
                    "bank carrying a steel W-beam guardrail, not a precast "
                    "concrete barrier. No joints exist to measure."
                ),
            },
            {
                "candidate": "Other repeating along-road structure",
                "verdict": "ABSENT",
                "what_was_measured": (
                    "One sign gantry, one direction sign, three round "
                    "signs -- all singletons. No lighting columns, no "
                    "bridge piers, no expansion joints, no distance "
                    "markers, no resolvable drainage grates."
                ),
            },
            {
                "candidate": "A second marking periodicity (divider 2)",
                "verdict": "PRESENT AND MEASURABLE AND CONTRADICTORY",
                "what_was_measured": (
                    "Consecutive, uniform dashes that read about 26 m per "
                    "step under the scale calibrated on divider 1's "
                    "assumed 18 m ladder -- see divider_disagreement "
                    "below. It falsifies the existing calibration rather "
                    "than anchoring it."
                ),
            },
        ],
        "divider_disagreement": {
            "what": (
                "The defect that removed the calibration block, and it is "
                "independent of whether 18 m is the right absolute period. "
                "Both dividers' surveyed dashes are consecutive and "
                "uniform, so under one road plane and one along-road scale "
                "they must give the same step."
            ),
            "assumed_period_m": survey["divider_lines"]["assumed_period_m"],
            "by_horizon_row": [
                {
                    "horizon_row": s["horizon_row"],
                    "divider_1_fit_rms_m": s["divider_1_rms_m"],
                    "divider_2_step_m": s["divider_2_step_m"],
                    "ratio": s["ratio"],
                }
                for s in steps
            ],
            "ratio_range": [
                min(s["ratio"] for s in steps),
                max(s["ratio"] for s in steps),
            ],
            "escape_hatch_closed": {
                "what": (
                    "The horizon row that would make divider 2 read 18 m."
                ),
                "horizon_row": reconciling["horizon_row"],
                "divider_2_step_m": reconciling["divider_2_step_m"],
                "divider_1_fit_rms_m": reconciling["divider_1_rms_m"],
                "verdict": (
                    "It destroys divider 1's own ladder and sits far below "
                    "the visible horizon, so it is not a horizon row. "
                    "Camera roll can move the divider-2 figure by at most "
                    "about 3 %. There is no way to reconcile them."
                ),
            },
            "uniformity_in_the_perspective_free_coordinate": uniformity,
            "uniformity_note": (
                "Equal world spacing is equal spacing in u = 1 / (vp_x - "
                "x), whatever the perspective. Both lines are uniform "
                "there and divider 2 -- the disputed one -- is the MORE "
                "uniform of the two, so the inconsistency is not one "
                "misplaced centroid. Whatever is wrong is wrong about the "
                "two lines' relationship."
            ),
            "cause": {
                "identified": False,
                "candidates_still_open": [
                    "the two lines are not parallel (a taper or diverge, "
                    "or more road curvature than assumed)",
                    "the road plane is not planar over the surveyed range "
                    "(the camera is on a bridge and the road may dip)",
                    "the divider-2 correspondences are mis-surveyed",
                    "divider 2 carries a different marking type",
                ],
                "new_evidence": (
                    "The three road-parallel image lines do not concur. "
                    "The guardrail -- 110 sub-pixel points over 580 px, and "
                    "wholly independent of the divider survey -- meets "
                    "divider 1 within 7 px of the surveyed vanishing point "
                    "but meets divider 2 nearly four times further out, "
                    "and the two dividers meet each other furthest of all. "
                    "The disagreement is therefore not symmetric between "
                    "the two lines: divider 2 is the outlier against an "
                    "independent reference. A Monte Carlo over plausible "
                    "reading error puts those separations at only 1 to 3 "
                    "sigma, so this narrows the candidates without "
                    "settling them."
                ),
                "what_was_NOT_done": (
                    "No marking standard was guessed to reconcile the two "
                    "lines. Guessing a standard is the error that produced "
                    "the falsified 18 m in the first place."
                ),
            },
            "vanishing_points": vanishing_point_spread(survey),
        },
        "why_the_calibration_was_removed_rather_than_refitted": {
            "attempted_repair": (
                "Drop the disputed divider-2 correspondences and refit on "
                "divider 1 alone with an honest holdout."
            ),
            "outcome": "IMPOSSIBLE",
            "error": refit_outcome,
            "reason": (
                "Divider 1's six surveyed points lie on one straight line "
                "in the image -- straight to "
                f"{fit_line(divider_1_image)[3]:.3f} px maximum residual "
                "over a 354 px span -- and at one cross-road offset in the "
                "world. A collinear configuration determines no homography "
                "at all. The disputed divider-2 points were the ONLY "
                "cross-road information the survey ever had, so the "
                "calibration could not be repaired by subsetting it."
            ),
            "removed_calibration_residuals_for_the_record": {
                "self_fit_mean_m": self_fit["mean_m"],
                "self_fit_max_m": self_fit["max_m"],
                "holdout_mean_m": holdout["mean_m"],
                "holdout_max_m": holdout["max_m"],
                "note": (
                    "A 0.12 m self-fit residual over correspondences that "
                    "disagree with each other by a factor of 1.46. The "
                    "out-of-sample figure is about three times worse and "
                    "was already a warning in the config's own comment."
                ),
            },
        },
        "the_one_clean_measurement": {
            "what": (
                "The guardrail beam. Committed as a regression fixture "
                "because it is the best independent check on the direction "
                "of the road available in this clip, and it costs nothing."
            ),
            "fixture": "data/fixtures/motorway_scale_survey.json",
            "tracked_columns": len(survey["guardrail_beam"]["points_px"]),
            "line": {"slope": rail_slope, "intercept": rail_intercept},
            "robust_weighted_residual_rms_px": rail_rms,
            "plain_residual_rms_px": rail_plain_rms,
            "plain_residual_max_px": rail_plain_max,
            "inliers_within_0_5px": survey["guardrail_beam"]["fit"][
                "inliers_within_0_5px"
            ],
            "honesty_note": (
                "The 0.243 px figure is a WEIGHTED rms from a robust fit "
                "and describes the beam, not every tracked column: about a "
                "tenth of the columns lock onto cast shadow or dead "
                "vegetation under the beam and sit several pixels off. "
                "Both figures are published so the robust one is not read "
                "as if it described all of them."
            ),
            "parallel_to_the_road": {
                "surveyed_vanishing_point_px": [vp_x, vp_y],
                "rail_row_at_that_column_px": rail_slope * vp_x + rail_intercept,
                "agreement_px": abs((rail_slope * vp_x + rail_intercept) - vp_y),
            },
            "also_shows": (
                "Straightness at a quarter of a pixel over 580 px bounds "
                "lens distortion in the region every other measurement in "
                "this investigation was made in."
            ),
        },
        "suggestive_but_explicitly_not_an_anchor": {
            "the_convergence": (
                "If the true period were the ~12.2 m the delineator posts "
                "point to, the measured 0.499 stroke:period duty would put "
                "the painted stroke at 6.08 m -- exactly the standard 6 m "
                "stroke -- whereas an 18 m period puts it at 8.97 m, which "
                "matches no German marking."
            ),
            "why_it_is_not_an_anchor": (
                "It rests entirely on the delineator measurement, which "
                "this same investigation rejects as unsound (non-uniform "
                "by 15 %, on a curving section, and matching no standard "
                "spacing). Both halves have to be said together."
            ),
            "the_roadworks_hypothesis": (
                "Unusual marking geometry, unreadable round "
                "speed-restriction signs and separately-measured slow "
                "dense traffic are consistent with a roadworks layout. "
                "That is a HYPOTHESIS, not an anchor: it explains why no "
                "standard fits without rescuing the scale, and guessing "
                "roadworks marking geometry would repeat the original "
                "error."
            ),
        },
        "honest_bracket_on_the_along_road_scale": {
            "upper_m": 18.0,
            "lower_m": 12.2,
            "band_percent": [-33.0, 0.0],
            "propagation": (
                "Scale error transfers to speed one for one, so this is a "
                "band of about minus 33 % on every speed. A figure "
                "published as 'V km/h, somewhere between 0.67 V and V' is "
                "not a speed figure. Publishing nothing is the defensible "
                "product, and no km/h number for this clip appears "
                "anywhere in this report by design."
            ),
        },
        "what_this_clip_still_licenses": [
            "counts and flow rate",
            "occupancy",
            "headway in seconds",
            "lane changes",
            "direction and wrong-way detection",
            "speed RATIOS between vehicles",
        ],
        "consequences_of_shipping_uncalibrated": [
            "Every speed reported for this clip is None.",
            "Stopped-vehicle detection never fires on it: that feature "
            "requires calibrated speed by design.",
            "The speed-limit violation feature can only be demonstrated on "
            "this clip with a limit the user sets explicitly. The posted "
            "limit in the footage is NOT legible -- upscaled 8x, the "
            "digits cannot be read -- so no published figure references "
            "it and no speed distribution is validated against it.",
        ],
        "what_would_change_this": (
            "A capture of the same site with a visible ground-truth "
            "baseline, or GNSS-tracked probe-vehicle passes. Not more "
            "analysis of this clip."
        ),
        "do_not_resurrect_without_new_evidence": [
            "Vehicle-footprint scale checks: they measure the cross-road "
            "axis, and the two world axes carry independent scales.",
            "Guardrail post spacing: dead unless a higher-resolution or "
            "lower-viewpoint capture of the same site appears. The matched "
            "controls above are the bar any revival must clear.",
        ],
        "reproduce": (
            "PYTHONPATH=src .venv/bin/python scripts/bench_speed.py "
            "--figures; PYTHONPATH=src .venv/bin/python -m pytest "
            "tests/test_scale_survey.py"
        ),
    }


# --- figures ------------------------------------------------------------------


def write_figures(synthetic: dict, real: dict, out_dir: Path) -> list[Path]:
    """matplotlib is imported here, not at module scope, so the JSON half
    of this script runs without it."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    out_dir.mkdir(parents=True, exist_ok=True)
    written = []

    # 1. zero-noise error by speed band, both chains
    figure, axes = plt.subplots(figsize=(7.5, 4.4))
    zero = synthetic["zero_noise"]
    bands = [row["speed_kmh"] for row in zero["full_chain"]["by_band"]]
    axes.plot(
        bands,
        [row["max_abs_error_kmh"] for row in zero["full_chain"]["by_band"]],
        "o-",
        label="full chain (tracker + homography + speed)",
    )
    axes.plot(
        bands,
        [
            row["max_abs_error_kmh"]
            for row in zero["homography_chain_only"]["by_band"]
        ],
        "s-",
        label="homography + speed only (tracker bypassed)",
    )
    axes.axhline(0.1, color="crimson", ls="--", lw=1, label="0.1 km/h requirement")
    axes.set_yscale("log")
    axes.set_xlabel("true speed (km/h)")
    axes.set_ylabel("max |error| over settled samples (km/h)")
    axes.set_title(
        "Synthetic scene, zero noise: the residual is the Kalman lag, "
        "and only that"
    )
    axes.grid(alpha=0.3, which="both")
    axes.legend(fontsize=8)
    figure.tight_layout()
    path = out_dir / "speed_zero_noise_by_band.png"
    figure.savefig(path, dpi=130)
    plt.close(figure)
    written.append(path)

    # 2. noise sweep
    figure, axes = plt.subplots(figsize=(7.5, 4.4))
    rows = [r for r in synthetic["noise_sweep"] if r["overall"]["n"] > 0]
    multiples = [r["sigma_multiple_of_measured_std"] for r in rows]
    axes.plot(
        multiples, [r["overall"]["rmse_kmh"] for r in rows], "o-", label="RMSE"
    )
    axes.axvline(
        1.0, color="seagreen", ls="--", lw=1, label="measured sigma (std_px)"
    )
    # RMSE is strictly positive at every swept sigma, so a plain log
    # axis is correct here; symlog would draw a meaningless negative
    # half. It spans 0.04 to 11 km/h, which linear would flatten.
    axes.set_yscale("log")
    axes.set_xlabel("sigma, as a multiple of the measured per-component vector")
    axes.set_ylabel("settled-sample RMSE (km/h)")
    axes.set_title("Synthetic scene: degradation with box noise")
    twin = axes.twinx()
    twin.bar(
        multiples,
        [
            100.0 * r["vehicles_the_tracker_lost"] / max(1, r["vehicles_offered"])
            for r in rows
        ],
        width=0.12,
        alpha=0.25,
        color="darkorange",
        label="vehicles lost by the tracker",
    )
    twin.set_ylabel("% of vehicles the tracker lost")
    axes.grid(alpha=0.3)
    handles, labels = axes.get_legend_handles_labels()
    extra = twin.get_legend_handles_labels()
    axes.legend(handles + extra[0], labels + extra[1], fontsize=8, loc="upper left")
    figure.tight_layout()
    path = out_dir / "speed_noise_sweep.png"
    figure.savefig(path, dpi=130)
    plt.close(figure)
    written.append(path)

    # 3. Tier 2: the two dividers disagree at every horizon row
    figure, axes = plt.subplots(figsize=(7.5, 4.4))
    rows = real["divider_disagreement"]["by_horizon_row"]
    axes.plot(
        [r["horizon_row"] for r in rows],
        [r["divider_2_step_m"] for r in rows],
        "o-",
        label="divider 2 step, measured",
    )
    axes.axhline(
        real["divider_disagreement"]["assumed_period_m"],
        color="crimson",
        ls="--",
        lw=1,
        label="divider 1's assumed 18 m period",
    )
    axes.set_xlabel("horizon row assumed (image y, px)")
    axes.set_ylabel("divider-2 along-road dash step (m)")
    axes.set_title(
        "Tier 2: the two lane dividers cannot both be 18 m, at any horizon"
    )
    axes.set_ylim(0, 30)
    axes.grid(alpha=0.3)
    axes.legend(fontsize=8)
    figure.tight_layout()
    path = out_dir / "speed_scale_disagreement.png"
    figure.savefig(path, dpi=130)
    plt.close(figure)
    written.append(path)

    return written


def main(argv=None) -> int:
    args = parse_args(argv)

    noise_report = json.loads(resolve(args.noise).read_text())
    synthetic = run_tier_1(noise_report)
    real = run_tier_2(load_scale_survey())

    if args.figures:
        figures = write_figures(synthetic, real, resolve(args.figure_dir))
        names = [str(p.relative_to(ROOT)) for p in figures]
        synthetic["figures"] = names[:2]
        real["figures"] = names[2:]

    for path, report in (
        (resolve(args.synthetic_out), synthetic),
        (resolve(args.real_out), real),
    ):
        write_report(path, report)
        print(f"wrote {path.relative_to(ROOT)}")

    print(
        f"  Tier 1 zero noise, homography chain: max "
        f"{synthetic['zero_noise']['homography_chain_only']['settled']['max_abs_error_kmh']:.6f} km/h"
    )
    print(
        f"  Tier 1 zero noise, full chain:       max "
        f"{synthetic['zero_noise']['full_chain']['settled']['max_abs_error_kmh']:.4f} km/h"
    )
    print(f"  Tier 1 monotonic under noise:        {synthetic['monotonic']}")
    print(
        f"  Check C max disagreement:            "
        f"{synthetic['check_c']['max_abs_difference_kmh']:.4f} km/h"
    )
    print(
        f"  Tier 2 absolute speed published:     "
        f"{real['absolute_speed_published']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
