#!/usr/bin/env python3
"""Bake ``reports/*.json`` into ``web/src/generated/reports.ts``.

Every measured number the site prints comes from this file, so the page cannot
drift from what was measured. The pattern is the one
``scripts/export_constants.py`` established: a generator with a narrow,
declarative contract, a committed artefact, and a sync test that fails whichever
side moved -- see ``tests/test_site_data_sync.py``.

Why a projection rather than the whole of ``reports/``:

    The seven report files are about 700 kB of JSON and carry per-frame
    false-positive lists thousands of entries long. Shipping them whole would
    put a megabyte of benchmark internals into a page bundle. So this script
    publishes a DECLARED subset -- ``PUBLISHED`` below -- and every mechanism
    here exists to stop that subset becoming a quiet, unnoticed one:

      * every field names an explicit path into its source, and an unresolvable
        path refuses the whole export rather than emitting a hole;
      * every report file present in ``reports/`` must be declared, so a new
        benchmark cannot be silently left off the site;
      * duplicate keys within one group are refused, because the loser of the
        collision would vanish and the artefact would still regenerate
        byte-identically -- exactly the failure byte equality cannot see;
      * the six derived values name their inputs and their formula, and the sync
        test recomputes each one from the source JSON independently.

Two things are deliberately NOT published, and the generator refuses to run if
either becomes reachable:

    ``parity.realClip.maxSpeedKmh`` and the two speed counts beside it. They are
    absolute km/h derived from ``motorway-a40.webm``, whose along-road scale is
    bracketed at -33 %/+0 % because no independent along-road anchor exists in
    the footage -- see ``reports/speed_real.json``. A number with that bracket is
    not a speed, ``configs/motorway.yaml`` ships with no calibration block, and
    the engine returns ``None`` for speed on that clip by design. Publishing the
    figure anywhere on the page would re-assert a claim the project's own
    measurement withdrew, so the redaction is enforced here, at the boundary,
    rather than left to whoever writes the next section.

Usage:

    PYTHONPATH=src .venv/bin/python scripts/build_site_data.py

The reports are read as data and never executed, and the output is a pure
function of the inputs: no timestamp, no machine name, no directory listing
order. That is what lets `npm run build` reproduce `docs/` byte for byte.
"""

import argparse
import json
import math
import re
import sys
from pathlib import Path
from typing import Callable, NamedTuple, cast

ROOT = Path(__file__).resolve().parents[1]

DEFAULT_REPORTS = ROOT / "reports"
DEFAULT_MODEL_CARD = ROOT / "web" / "public" / "models" / "MODEL_CARD.md"
DEFAULT_OUT = ROOT / "web" / "src" / "generated" / "reports.ts"

HEADER = (
    "// generated by scripts/build_site_data.py — do not edit\n"
    "//\n"
    "// Source of truth: reports/*.json, plus the int8 comparison table in\n"
    "// web/public/models/MODEL_CARD.md. Re-run the generator after a benchmark\n"
    "// and tests/test_site_data_sync.py fails while this file and those disagree.\n"
    "//\n"
    "// No absolute km/h from motorway-a40.webm is published here. That clip has no\n"
    "// independent along-road anchor, its scale is bracketed at -33 %/+0 %, and the\n"
    "// engine returns null for speed on it by design.\n"
)

Path_ = tuple[object, ...]


class SourceContractError(Exception):
    """A report, the model card, or the spec itself broke the contract."""


# -- the declaration vocabulary ------------------------------------------------
#
# Five field kinds and one derivation, and no more: anything that needs a sixth
# is a sign the page wants a shape the reports do not have.


class Value(NamedTuple):
    """One scalar, published under ``key``."""

    key: str
    path: Path_


class Series(NamedTuple):
    """A list of scalars, published verbatim and in source order."""

    key: str
    path: Path_


class Group(NamedTuple):
    """A nested object. Field paths are relative to ``path``."""

    key: str
    path: Path_
    fields: tuple


class Rows(NamedTuple):
    """A list of objects, each projected with ``fields``."""

    key: str
    path: Path_
    fields: tuple


class Keyed(NamedTuple):
    """A dict of objects, flattened to a list with the dict key kept.

    The reports key several tables by a name that is not a legal identifier --
    ``engine+gate``, ``box_jitter@sigma=2 px`` -- and an array of rows carrying
    that name in a field is both easier to render and stable under iteration
    order, which ``dict`` preserves from the file.
    """

    key: str
    path: Path_
    name: str
    fields: tuple


class Derived(NamedTuple):
    """A value computed from other measured values.

    ``inputs`` are resolved and handed to ``compute`` in order. ``why`` states
    the formula in words, because a derived number on a page about measurement
    has to say how it was arrived at.
    """

    key: str
    inputs: tuple[Path_, ...]
    compute: Callable[..., object]
    why: str


class Report(NamedTuple):
    """One source file and the section it produces."""

    key: str
    file: str
    fields: tuple


class Redaction(NamedTuple):
    """A path that exists in the source and must never reach the output."""

    file: str
    path: Path_
    reason: str


# -- resolution ----------------------------------------------------------------


def pointer(path: Path_) -> str:
    return "/".join(str(step) for step in path)


def resolve(document: object, path: Path_, origin: str) -> object:
    """The value at ``path``, or a refusal naming the pointer that broke.

    A missing path is never tolerated. The alternative -- emitting ``null`` and
    moving on -- is how a projection becomes a subset nobody notices: the
    artefact still regenerates byte-identically, so the sync test stays green
    while the page has quietly stopped showing a result.
    """
    here: object = document
    for index, step in enumerate(path):
        walked = pointer(path[: index + 1])
        if isinstance(step, int):
            if not isinstance(here, list):
                raise SourceContractError(
                    f"{origin}:{walked}: expected a list, found {type(here).__name__}"
                )
            if step >= len(here):
                raise SourceContractError(
                    f"{origin}:{walked}: index {step} is past the end "
                    f"({len(here)} items)"
                )
            here = here[step]
            continue
        if not isinstance(here, dict):
            raise SourceContractError(
                f"{origin}:{walked}: expected an object, found {type(here).__name__}"
            )
        if step not in here:
            raise SourceContractError(
                f"{origin}:{walked}: no such key (the report has "
                f"{sorted(here)[:8]}…)"
            )
        here = here[step]
    return here


def check_scalar(value: object, where: str) -> object:
    if value is None or isinstance(value, (bool, int, str)):
        return value
    if isinstance(value, float):
        if not math.isfinite(value):
            # json.dumps would emit `NaN` or `Infinity`, neither of which is a
            # TypeScript literal, so this would produce a file that does not
            # compile.
            raise SourceContractError(f"{where}: {value!r} is not finite")
        return value
    raise SourceContractError(
        f"{where}: {type(value).__name__} is not a scalar; declare it as a "
        f"Series, Rows or Group instead"
    )


def project(document: object, fields: tuple, origin: str, base: Path_ = ()) -> dict:
    """Apply ``fields`` to ``document``, returning a plain dict.

    Refuses duplicate keys. A collision would drop whichever field lost, and the
    hole would survive every regeneration, so byte equality could never see it --
    the same trap ``export_constants.py`` guards with its emitted-count check.
    """
    seen: list[str] = [field.key for field in fields]
    duplicates = sorted({key for key in seen if seen.count(key) > 1})
    if duplicates:
        raise SourceContractError(
            f"{origin}:{pointer(base) or '/'}: duplicate keys {duplicates}; one "
            f"of each pair would be dropped silently"
        )

    out: dict[str, object] = {}
    for field in fields:
        path = base + field.path if not isinstance(field, Derived) else base
        where = f"{origin}:{pointer(path) or '/'}"
        if isinstance(field, Value):
            out[field.key] = check_scalar(resolve(document, path, origin), where)
        elif isinstance(field, Series):
            found = resolve(document, path, origin)
            if not isinstance(found, list):
                raise SourceContractError(
                    f"{where}: Series needs a list, found {type(found).__name__}"
                )
            out[field.key] = [
                check_scalar(item, f"{where}/{i}") for i, item in enumerate(found)
            ]
        elif isinstance(field, Group):
            resolve(document, path, origin)  # refuse early if the group is gone
            out[field.key] = project(document, field.fields, origin, path)
        elif isinstance(field, Rows):
            found = resolve(document, path, origin)
            if not isinstance(found, list):
                raise SourceContractError(
                    f"{where}: Rows needs a list, found {type(found).__name__}"
                )
            out[field.key] = [
                project(document, field.fields, origin, path + (index,))
                for index in range(len(found))
            ]
        elif isinstance(field, Keyed):
            found = resolve(document, path, origin)
            if not isinstance(found, dict):
                raise SourceContractError(
                    f"{where}: Keyed needs an object, found {type(found).__name__}"
                )
            rows = []
            for name in found:
                row = {field.name: name}
                row.update(project(document, field.fields, origin, path + (name,)))
                rows.append(row)
            out[field.key] = rows
        elif isinstance(field, Derived):
            values = [resolve(document, base + p, origin) for p in field.inputs]
            out[field.key] = check_scalar(field.compute(*values), where)
        else:  # pragma: no cover -- the vocabulary is closed
            raise SourceContractError(f"{where}: unknown field kind {field!r}")

        if len(out) != seen.index(field.key) + 1:  # pragma: no cover
            raise SourceContractError(
                f"{where}: {field.key} did not reach the output"
            )
    return out


# -- the derived values --------------------------------------------------------
#
# Six, and each one is arithmetic on figures the reports measured. They exist
# because the alternative is a number typed into the page's prose, which the bake
# cannot protect.


def f1(true_positives: float, predicted: float, truth: float) -> float:
    return 2.0 * true_positives / (predicted + truth)


def one_event_f1_delta(true_positives: int, predicted: int, truth: int) -> float:
    """How far one phantom event moves F1 at the engine's own operating point.

    The ground-truth set has 17 crossings, so a single added or removed event is
    a large fraction of every rate on this page. Printing F1 to more digits than
    this invites a precision the measurement does not have, and any two methods
    closer together than this differ by one event rather than in quality.
    """
    return abs(
        f1(true_positives, predicted, truth) - f1(true_positives, predicted - 1, truth)
    )


def one_event_precision_delta(truth: int) -> float:
    """The same resolution on precision: one event in a set of ``truth``."""
    return 1.0 / truth


def cpu_multiple(engine_ms: float, baseline_ms: float) -> float:
    """What the engine's Kalman filter and second association stage cost.

    Both figures are the tracker and the counting rule only, on cached
    detections, so this is the association cost and excludes the detector
    entirely -- which is by far the larger cost in a real session.
    """
    return engine_ms / baseline_ms


def scaled_stress(multiple: float, at_sigma: float, to_sigma: float) -> float:
    """A jitter stress multiple moved from one sigma to another.

    The sweep's knob is a per-corner sigma and the stress multiple is that sigma
    over the measured residual, so it is linear in sigma: the multiple at 2 px is
    the multiple at 8 px times 2/8.
    """
    return multiple * to_sigma / at_sigma


# -- what is published ---------------------------------------------------------

COUNTING = (
    Value("protocol", ("protocol",)),
    Value("groundTruth", ("ground_truth",)),
    Value("clip", ("clip",)),
    Value("fps", ("fps",)),
    Value("frames", ("frames",)),
    Group(
        "gate",
        ("gate",),
        (
            Value("name", ("name",)),
            Value("labelPositive", ("label_positive",)),
            Value("labelNegative", ("label_negative",)),
        ),
    ),
    Group(
        "detector",
        ("detector",),
        (
            Value("model", ("model",)),
            Value("confidence", ("confidence",)),
            Value("imgsz", ("imgsz",)),
            Series("classes", ("classes",)),
        ),
    ),
    Group(
        "labels",
        ("labels",),
        (
            Value("total", ("total",)),
            Value("certain", ("certain",)),
            Value("probable", ("probable",)),
        ),
    ),
    Group(
        "matchWindow",
        ("match_window",),
        (
            Value("framesBefore", ("frames_before",)),
            Value("framesAfter", ("frames_after",)),
            Value("reason", ("reason",)),
        ),
    ),
    Group(
        "matching",
        ("matching",),
        (
            Value("rule", ("rule",)),
            Value("limitation", ("limitation",)),
            Value("greedyEqualsMaxCardinality", ("greedy_equals_max_cardinality",)),
        ),
    ),
    Keyed(
        "methods",
        ("methods",),
        "method",
        (
            Value("nPredicted", ("full", "n_predicted")),
            Value("nGroundTruth", ("full", "n_ground_truth")),
            Value("truePositives", ("full", "true_positives")),
            Value("precision", ("full", "precision")),
            Value("recall", ("full", "recall")),
            Value("f1", ("full", "f1")),
            Value("countError", ("full", "count_error")),
            Value("classConsistency", ("full", "class_consistency", "rate")),
            Value("certainOnlyF1", ("certain_only", "f1")),
        ),
    ),
    Keyed(
        "timing",
        ("timing",),
        "method",
        (Value("msPerFrame", ("ms_per_frame",)), Value("frames", ("frames",))),
    ),
    Group(
        "bandSweep",
        ("band_sweep",),
        (
            Value("tracker", ("tracker",)),
            Value("approachPxPerFrame", ("median_gate_approach_px_per_frame",)),
            Value("note", ("note",)),
            Value("entriesNote", ("entries_note",)),
            Rows(
                "entries",
                ("entries",),
                (
                    Value("bandPx", ("band_px",)),
                    Value("nPredicted", ("n_predicted",)),
                    Value("truePositives", ("true_positives",)),
                    Value("missRate", ("miss_rate",)),
                    Value("phantomRate", ("phantom_rate",)),
                    Value("f1", ("f1",)),
                ),
            ),
        ),
    ),
    Group(
        "resolution",
        (),
        (
            Derived(
                "oneEventF1",
                (
                    ("methods", "engine+gate", "full", "true_positives"),
                    ("methods", "engine+gate", "full", "n_predicted"),
                    ("labels", "total"),
                ),
                one_event_f1_delta,
                "F1 at the engine's operating point, minus F1 with one fewer "
                "prediction and the same matches",
            ),
            Derived(
                "oneEventPrecision",
                (("labels", "total"),),
                one_event_precision_delta,
                "one event in the labelled set: 1 / labels.total",
            ),
        ),
    ),
    Derived(
        "engineCpuMultiple",
        (
            ("timing", "engine+gate", "ms_per_frame"),
            ("timing", "centroid+gate", "ms_per_frame"),
        ),
        cpu_multiple,
        "engine+gate ms/frame divided by centroid+gate ms/frame, tracker and "
        "counting rule only",
    ),
    Series("caveats", ("caveats",)),
)

ROBUSTNESS_LEVEL_METHODS = (
    Value("precision", ("precision",)),
    Value("recall", ("recall",)),
    Value("f1", ("f1",)),
    Value("nPredicted", ("n_predicted",)),
    Value("truePositives", ("true_positives",)),
)

ROBUSTNESS = (
    Value("protocol", ("protocol",)),
    Value("baselineReport", ("baseline_report",)),
    Value("clip", ("clip",)),
    Value("fps", ("fps",)),
    Value("frames", ("frames",)),
    Value("seed", ("seed",)),
    Group("labels", ("labels",), (Value("total", ("total",)),)),
    Group(
        "reduction",
        ("reduction",),
        (Value("claim", ("claim",)),),
    ),
    Keyed(
        "protocols",
        ("protocols",),
        "name",
        (
            Value("knob", ("knob",)),
            Value("seeded", ("seeded",)),
            Value("note", ("note",)),
            Series("levels", ("levels",)),
            Rows(
                "entries",
                ("entries",),
                (
                    Value("level", ("level",)),
                    Value("levelLabel", ("level_label",)),
                    Value("framesKept", ("frames_kept",)),
                    Value("framesTotal", ("frames_total",)),
                    Value("detectionsKept", ("detections_kept",)),
                    Value("detectionsTotal", ("detections_total",)),
                    Value("maxGapFrames", ("max_gap_frames",)),
                    Value("windowWidenedBy", ("window_widened_by_frames",)),
                    Value("recallCeiling", ("resolution", "reachability", "recall_ceiling")),
                    Group("engine", ("methods", "engine+gate"), ROBUSTNESS_LEVEL_METHODS),
                    Group("centroid", ("methods", "centroid+gate"), ROBUSTNESS_LEVEL_METHODS),
                    Group("greedyIou", ("methods", "greedy-iou+gate"), ROBUSTNESS_LEVEL_METHODS),
                ),
            ),
        ),
    ),
    Group(
        "jitter",
        ("jitter_calibration",),
        (
            Value("sourceReport", ("source_report",)),
            Value("note", ("note",)),
            Value("medianBoxWidthPx", ("median_box_width_px",)),
            Value("medianBoxHeightPx", ("median_box_height_px",)),
            Group(
                "cornerSigmaEquivalentPx",
                ("corner_sigma_equivalent_px",),
                (
                    Value("method", ("method",)),
                    Value("minPx", ("min_px",)),
                    Value("maxPx", ("max_px",)),
                ),
            ),
            Group(
                "stressAtMaxSigma",
                ("stress_multiple_at_max_sigma",),
                (
                    Value("sigmaPx", ("sigma_px",)),
                    Value("lowest", ("lowest",)),
                    Value("highest", ("highest",)),
                ),
            ),
            Group(
                "stressAtSigma2",
                (),
                (
                    Derived(
                        "lowest",
                        (
                            ("stress_multiple_at_max_sigma", "lowest"),
                            ("stress_multiple_at_max_sigma", "sigma_px"),
                        ),
                        lambda lowest, sigma: scaled_stress(lowest, sigma, 2.0),
                        "the sigma=8 px stress multiple scaled to sigma=2 px, "
                        "which is linear in sigma",
                    ),
                    Derived(
                        "highest",
                        (
                            ("stress_multiple_at_max_sigma", "highest"),
                            ("stress_multiple_at_max_sigma", "sigma_px"),
                        ),
                        lambda highest, sigma: scaled_stress(highest, sigma, 2.0),
                        "the sigma=8 px stress multiple scaled to sigma=2 px, "
                        "which is linear in sigma",
                    ),
                ),
            ),
        ),
    ),
    Group(
        "associationFloor",
        ("association_floor_ablation",),
        (
            Value("shippedFloor", ("shipped_floor",)),
            Series("floors", ("floors",)),
            Value("comparisonFloorSource", ("comparison_floor_source",)),
            Value("heldFixed", ("held_fixed",)),
            Value("gainThreshold", ("gain_threshold",)),
            Value("loosestHelps", ("loosening_the_floor_helps",)),
            Series("explains", ("protocols_the_floor_explains",)),
            Series("doesNotExplain", ("protocols_the_floor_does_not_explain",)),
            Group(
                "largestGain",
                ("largest_f1_gain",),
                (
                    Value("protocol", ("protocol",)),
                    Value("levelLabel", ("level_label",)),
                    Value("gain", ("gain",)),
                ),
            ),
            Keyed(
                "largestGainByProtocol",
                ("largest_f1_gain_by_protocol",),
                "name",
                (Value("levelLabel", ("level_label",)), Value("gain", ("gain",))),
            ),
            # The whole ablation, level by level, because the IDENTITY rows are
            # the evidence that the shipped floor is not simply worse: at every
            # protocol's undegraded level the looser floor recovers nothing. A
            # table that showed only the levels where loosening helps would read
            # as "0.3 is better", which the measurement does not say. The source
            # keys are the two floors as strings, so a change to either refuses
            # the bake rather than silently publishing the wrong column.
            Keyed(
                "byProtocol",
                ("by_protocol",),
                "name",
                (
                    Rows(
                        "entries",
                        (),
                        (
                            Value("levelLabel", ("level_label",)),
                            Value("f1Shipped", ("f1", "0.8")),
                            Value("f1Loosened", ("f1", "0.3")),
                            Value("predictedShipped", ("n_predicted", "0.8")),
                            Value("predictedLoosened", ("n_predicted", "0.3")),
                        ),
                    ),
                ),
            ),
            Value("verdict", ("verdict",)),
        ),
    ),
    Group(
        "trackerSeparation",
        ("questions", "tracker_separation"),
        (
            Series("methodsCompared", ("methods_compared",)),
            Value("levelsMeasured", ("levels_measured",)),
            Value("maxF1Spread", ("max_f1_spread",)),
            Series("levelsWhereTrackersDiffer", ("levels_where_trackers_differ",)),
            Series("levelsWhereEngineLowest", ("levels_where_the_engine_scores_lowest",)),
            Value("engineLeadsAnyDegradedLevel", ("engine_leads_at_any_degraded_level",)),
            Value("separateUndegraded", ("trackers_separate_on_undegraded_footage",)),
            Value("engineLowestOnEveryIdentityLevel", ("engine_lowest_on_every_identity_level",)),
            Value("maxIdentityF1Spread", ("max_identity_f1_spread",)),
            Series("identityLevels", ("identity_levels_compared",)),
            Value("verdict", ("verdict",)),
        ),
    ),
    Group(
        "bandStepOver",
        ("questions", "band_step_over"),
        (Value("verdict", ("verdict",)),),
    ),
    Series("caveats", ("caveats",)),
)

#: The clean block carries every metric, because that is the table the page
#: prints in full. The 21 degradation levels carry only the two the sweep is
#: about -- publishing the rest would put four figures per tracker per level into
#: the bundle that nothing renders.
TRACKING_CLEAN_TRACKERS = (
    Value("gateRegionTrackIds", ("gate_region_track_ids",)),
    Value("crossingTrackIds", ("crossing_track_ids",)),
    Value("fragmentationRatio", ("fragmentation_ratio",)),
    Value("identityDeviation", ("identity_deviation",)),
    Value("crossingIdRatio", ("crossing_id_ratio",)),
    Value("classConsistency", ("class_consistency", "rate")),
)

TRACKING_LEVEL_TRACKERS = (
    Value("fragmentationRatio", ("fragmentation_ratio",)),
    Value("identityDeviation", ("identity_deviation",)),
)

TRACKING = (
    Value("protocol", ("protocol",)),
    Value("clip", ("clip",)),
    Value("frames", ("frames",)),
    Value("countingRule", ("counting_rule",)),
    Value("countingRuleNote", ("counting_rule_note",)),
    Series("trackersCompared", ("trackers_compared",)),
    Group("labels", ("labels",), (Value("total", ("total",)),)),
    Group(
        "gateRegion",
        ("gate_region",),
        (
            Value("halfWidthPx", ("half_width_px",)),
            Value("definition", ("definition",)),
            Value("sourceOfTheHalfWidth", ("source_of_the_half_width",)),
        ),
    ),
    Group(
        "metricDefinitions",
        ("metric_definitions",),
        (
            Group(
                "fragmentationRatio",
                ("fragmentation_ratio",),
                (
                    Value("definition", ("definition",)),
                    Value("denominator", ("denominator",)),
                    Value("notAClaim", ("not_a_claim",)),
                ),
            ),
            Group(
                "identityDeviation",
                ("identity_deviation",),
                (Value("definition", ("definition",)),),
            ),
            Group(
                "classConsistency",
                ("class_consistency",),
                (Value("definition", ("definition",)),),
            ),
        ),
    ),
    Group(
        "clean",
        ("clean",),
        (
            Value("levelLabel", ("level_label",)),
            Keyed("trackers", ("trackers",), "tracker", TRACKING_CLEAN_TRACKERS),
        ),
    ),
    Keyed(
        "protocols",
        ("protocols",),
        "name",
        (
            Value("knob", ("knob",)),
            Rows(
                "entries",
                ("entries",),
                (
                    Value("level", ("level",)),
                    Value("levelLabel", ("level_label",)),
                    Keyed("trackers", ("trackers",), "tracker", TRACKING_LEVEL_TRACKERS),
                ),
            ),
        ),
    ),
    Group(
        "cleanDegeneracy",
        ("questions", "clean_clip_degeneracy"),
        (
            Value("spread", ("spread",)),
            Value("classConsistencySpread", ("class_consistency_spread",)),
            Value("discriminates", ("discriminates",)),
            Value("verdict", ("verdict",)),
        ),
    ),
    Group(
        "separation",
        ("questions", "tracker_separation"),
        (
            Value("metric", ("metric",)),
            Value("maxSpread", ("max_spread",)),
            Value("levelsMeasured", ("levels_measured",)),
            Series("levelsWhereTrackersDiffer", ("levels_where_trackers_differ",)),
            Series(
                "levelsWhereEngineFurthest",
                ("levels_where_the_engine_is_furthest_and_they_differ",),
            ),
            Value("furthestTieRule", ("furthest_from_one_tie_rule",)),
            Value("verdict", ("verdict",)),
        ),
    ),
    Group(
        "agreement",
        ("questions", "agreement_with_crossing_f1"),
        (
            Value("criterion", ("criterion",)),
            Value("halfWidthPx", ("half_width_px",)),
            Series("levelsWhereF1Separates", ("levels_where_crossing_f1_separates",)),
            Series("levelsWhereTheyAgree", ("levels_where_the_two_agree",)),
            Series("levelsWhereTheyDisagree", ("levels_where_the_two_disagree",)),
            Value("agreesEverywhere", ("agrees_everywhere",)),
            Value("verdict", ("verdict",)),
        ),
    ),
    Group(
        "gateRegionSweep",
        ("gate_region_sweep",),
        (
            Value("why", ("why",)),
            Value("publishedHalfWidthPx", ("published_half_width_px",)),
            Series("halfWidthsPx", ("half_widths_px",)),
            Value("invariants", ("invariants_sentence",)),
        ),
    ),
    Rows(
        "claimsNotMade",
        ("claims_not_made",),
        (Value("claim", ("claim",)), Value("reason", ("reason",))),
    ),
    Series("caveats", ("caveats",)),
)

SPEED_BAND_STATS = (
    Value("n", ("n",)),
    Value("meanAbsErrorKmh", ("mean_abs_error_kmh",)),
    Value("maxAbsErrorKmh", ("max_abs_error_kmh",)),
    Value("rmseKmh", ("rmse_kmh",)),
    Value("meanRelativePercent", ("mean_relative_percent",)),
)

SPEED_SYNTHETIC = (
    Value("tier", ("tier",)),
    Value("whatThisIs", ("what_this_is",)),
    Value("limitations", ("limitations",)),
    Value("monotonic", ("monotonic",)),
    Value("monotonicNote", ("monotonic_note",)),
    Value("reproduce", ("reproduce",)),
    Group(
        "camera",
        ("camera",),
        (
            Value("focalPx", ("focal_px",)),
            Value("heightM", ("height_m",)),
            Value("pitchDeg", ("pitch_deg",)),
            Series("framePx", ("frame_px",)),
            Value("note", ("note",)),
        ),
    ),
    Group(
        "roadPlane",
        ("road_plane",),
        (
            Value("howFitted", ("how_fitted",)),
            Value("holdoutMaxErrorM", ("holdout_max_error_m",)),
            Value("holdoutMeanErrorM", ("holdout_mean_error_m",)),
        ),
    ),
    Group(
        "settled",
        ("settled_definition",),
        (Value("windowS", ("window_s",)), Value("meaning", ("meaning",))),
    ),
    Series("speedBandsKmh", ("speed_bands_kmh",)),
    Group(
        "noiseCalibration",
        ("noise_calibration",),
        (
            Value("source", ("source",)),
            Value("sourceCaveat", ("source_caveat",)),
            Value("sweepAnchoredOn", ("sweep_anchored_on",)),
            Value("why", ("why",)),
        ),
    ),
    Group(
        "homographyOnly",
        ("zero_noise", "homography_chain_only"),
        (
            Value("what", ("what",)),
            Value("requirementKmh", ("requirement_kmh",)),
            Group("settled", ("settled",), SPEED_BAND_STATS),
            Rows(
                "byBand",
                ("by_band",),
                (Value("speedKmh", ("speed_kmh",)), *SPEED_BAND_STATS),
            ),
        ),
    ),
    Group(
        "fullChain",
        ("zero_noise", "full_chain"),
        (
            Value("what", ("what",)),
            Group("settled", ("settled",), SPEED_BAND_STATS),
            Group(
                "allSamples",
                ("all_samples_including_start_up",),
                SPEED_BAND_STATS,
            ),
            Rows(
                "byBand",
                ("by_band",),
                (Value("speedKmh", ("speed_kmh",)), *SPEED_BAND_STATS),
            ),
        ),
    ),
    Group(
        "smoothingTrade",
        ("zero_noise", "smoothing_trade_off"),
        (
            Value("what", ("what",)),
            Value("sigma", ("sigma",)),
            Value("seeds", ("seeds",)),
            Value("vehiclesLost", ("vehicles_the_tracker_lost",)),
            Value("whyThatMatters", ("why_that_matters",)),
            Value("finding", ("finding",)),
            Rows(
                "byBand",
                ("by_band",),
                (
                    Value("speedKmh", ("speed_kmh",)),
                    Value("kalmanRmseKmh", ("kalman_anchor_rmse_kmh",)),
                    Value("rawRmseKmh", ("raw_detection_anchor_rmse_kmh",)),
                    Value("better", ("better",)),
                ),
            ),
        ),
    ),
    Group(
        "boxModel",
        ("zero_noise", "box_model_comparison"),
        (
            Value("what", ("what",)),
            Value("footprintRmseKmh", ("footprint_settled", "rmse_kmh")),
            Value("solidRmseKmh", ("solid_settled", "rmse_kmh")),
            Value("whyItBarelyMoves", ("why_it_barely_moves",)),
        ),
    ),
    Rows(
        "noiseSweep",
        ("noise_sweep",),
        (
            Value("sigmaMultiple", ("sigma_multiple_of_measured_std",)),
            Value("sigmaCentreYPx", ("sigma_px", "centre_y")),
            Value("sigmaBoxWidthPx", ("sigma_px", "box_width")),
            Value("vehiclesLost", ("vehicles_the_tracker_lost",)),
            Value("vehiclesOffered", ("vehicles_offered",)),
            Group("overall", ("overall",), SPEED_BAND_STATS),
        ),
    ),
    Group(
        "checkC",
        ("check_c",),
        (
            Value("what", ("what",)),
            Value("runOn", ("run_on",)),
            Value("whyNotOnRealFootage", ("why_not_on_real_footage",)),
            Value("gateSeparationM", ("gate_separation_m",)),
            Value("agreementRequirementKmh", ("agreement_requirement_kmh",)),
            Value("maxAbsDifferenceKmh", ("max_abs_difference_kmh",)),
        ),
    ),
)

SPEED_REAL = (
    Value("tier", ("tier",)),
    Value("clip", ("clip",)),
    Value("headline", ("headline",)),
    Value("absoluteSpeedPublished", ("absolute_speed_published",)),
    Value("shippedConfigCalibrated", ("shipped_config_calibrated",)),
    Value("limitations", ("limitations",)),
    Value("whatWouldChangeThis", ("what_would_change_this",)),
    Value("reproduce", ("reproduce",)),
    Rows(
        "anchorCandidates",
        ("anchor_candidates",),
        (
            Value("candidate", ("candidate",)),
            Value("verdict", ("verdict",)),
            Value("whatWasMeasured", ("what_was_measured",)),
        ),
    ),
    Group(
        "guardrailControls",
        ("anchor_candidates", 0),
        (
            Value("whyTheControlsMatter", ("why_the_controls_matter",)),
            Rows(
                "bands",
                ("matched_controls",),
                (
                    Value("band", ("band",)),
                    Value("meanPeriodU", ("mean_period_u",)),
                    Value("spreadPercent", ("spread_percent",)),
                ),
            ),
        ),
    ),
    Group(
        "delineators",
        ("anchor_candidates", 1),
        (Value("whyUnusable", ("why_unusable",)),),
    ),
    Group(
        "dividerDisagreement",
        ("divider_disagreement",),
        (
            Value("what", ("what",)),
            Value("assumedPeriodM", ("assumed_period_m",)),
            Series("ratioRange", ("ratio_range",)),
            Value("uniformityNote", ("uniformity_note",)),
            Rows(
                "byHorizonRow",
                ("by_horizon_row",),
                (
                    Value("horizonRow", ("horizon_row",)),
                    Value("divider1FitRmsM", ("divider_1_fit_rms_m",)),
                    Value("divider2StepM", ("divider_2_step_m",)),
                    Value("ratio", ("ratio",)),
                ),
            ),
            Group(
                "escapeHatchClosed",
                ("escape_hatch_closed",),
                (
                    Value("what", ("what",)),
                    Value("horizonRow", ("horizon_row",)),
                    Value("divider2StepM", ("divider_2_step_m",)),
                    Value("divider1FitRmsM", ("divider_1_fit_rms_m",)),
                    Value("verdict", ("verdict",)),
                ),
            ),
            Group(
                "cause",
                ("cause",),
                (
                    Value("identified", ("identified",)),
                    Series("candidatesStillOpen", ("candidates_still_open",)),
                    Value("newEvidence", ("new_evidence",)),
                ),
            ),
            Group(
                "vanishingPoints",
                ("vanishing_points",),
                (
                    Series("surveyed", ("surveyed_homography_vp",)),
                    Value(
                        "divider1xGuardrailPx",
                        ("pairs", "divider_1_x_guardrail", "distance_from_surveyed_vp_px"),
                    ),
                    Value(
                        "divider2xGuardrailPx",
                        ("pairs", "divider_2_x_guardrail", "distance_from_surveyed_vp_px"),
                    ),
                    Value(
                        "divider1xDivider2Px",
                        ("pairs", "divider_1_x_divider_2", "distance_from_surveyed_vp_px"),
                    ),
                ),
            ),
        ),
    ),
    Group(
        "whyRemoved",
        ("why_the_calibration_was_removed_rather_than_refitted",),
        (
            Value("attemptedRepair", ("attempted_repair",)),
            Value("outcome", ("outcome",)),
            Value("error", ("error",)),
            Value("reason", ("reason",)),
        ),
    ),
    Group(
        "cleanMeasurement",
        ("the_one_clean_measurement",),
        (
            Value("what", ("what",)),
            Value("fixture", ("fixture",)),
            Value("trackedColumns", ("tracked_columns",)),
            Value("robustWeightedRmsPx", ("robust_weighted_residual_rms_px",)),
            Value("plainRmsPx", ("plain_residual_rms_px",)),
            Value("plainMaxPx", ("plain_residual_max_px",)),
            Value("inliersWithinHalfPx", ("inliers_within_0_5px",)),
            Value("honestyNote", ("honesty_note",)),
            Value("alsoShows", ("also_shows",)),
        ),
    ),
    Group(
        "notAnAnchor",
        ("suggestive_but_explicitly_not_an_anchor",),
        (
            Value("theConvergence", ("the_convergence",)),
            Value("whyItIsNotAnAnchor", ("why_it_is_not_an_anchor",)),
            Value("roadworksHypothesis", ("the_roadworks_hypothesis",)),
        ),
    ),
    Group(
        "bracket",
        ("honest_bracket_on_the_along_road_scale",),
        (
            Value("upperM", ("upper_m",)),
            Value("lowerM", ("lower_m",)),
            Series("bandPercent", ("band_percent",)),
            Value("propagation", ("propagation",)),
        ),
    ),
    Series("stillLicenses", ("what_this_clip_still_licenses",)),
    Series("consequences", ("consequences_of_shipping_uncalibrated",)),
    Series("doNotResurrect", ("do_not_resurrect_without_new_evidence",)),
)

DETECTION_NOISE_RESIDUAL = (
    Value("n", ("n",)),
    Value("stdPx", ("std_px",)),
    Value("maePx", ("mae_px",)),
    Value("p95AbsPx", ("p95_abs_px",)),
)

DETECTION_NOISE = (
    Value("caveat", ("caveat",)),
    Value("association", ("association",)),
    Value("medianFilterFrames", ("median_filter_frames",)),
    Value("frames", ("frames",)),
    Value("tracksSeen", ("tracks_seen",)),
    Value("tracksContributing", ("tracks_contributing",)),
    Value("medianBoxWidthPx", ("median_box_width_px",)),
    Value("medianBoxHeightPx", ("median_box_height_px",)),
    Group(
        "residuals",
        ("residuals",),
        (
            Group("boxWidth", ("box_width",), DETECTION_NOISE_RESIDUAL),
            Group("boxHeight", ("box_height",), DETECTION_NOISE_RESIDUAL),
            Group("centreX", ("centre_x",), DETECTION_NOISE_RESIDUAL),
            Group("centreY", ("centre_y",), DETECTION_NOISE_RESIDUAL),
        ),
    ),
)

PARITY = (
    Value("caseCount", ("caseCount",)),
    Value("speedToleranceKmh", ("speedToleranceKmh",)),
    Series("straddleKinds", ("straddleKinds",)),
    Group(
        "iouStraddle",
        ("iouStraddle",),
        (
            Value("matchThresh", ("matchThresh",)),
            Value("iou", ("iou",)),
            Value("controlIou", ("controlIou",)),
            Value("controlIsOneUlpBelow", ("controlIsOneUlpBelow",)),
            Value("gatingChi2", ("gatingChi2",)),
            Value("gatingDistance", ("gatingDistance",)),
        ),
    ),
    Group(
        "realClip",
        ("realClip",),
        (
            Value("clip", ("clip",)),
            Value("startFrame", ("startFrame",)),
            Value("frames", ("frames",)),
            Value("detections", ("detections",)),
            Value("tracksAllocated", ("tracksAllocated",)),
            Value("events", ("events",)),
        ),
    ),
)

PUBLISHED = (
    Report("counting", "counting_accuracy.json", COUNTING),
    Report("robustness", "robustness.json", ROBUSTNESS),
    Report("tracking", "tracking.json", TRACKING),
    Report("speedSynthetic", "speed_synthetic.json", SPEED_SYNTHETIC),
    Report("speedReal", "speed_real.json", SPEED_REAL),
    Report("detectionNoise", "detection_noise.json", DETECTION_NOISE),
    Report("parity", "parity.json", PARITY),
)

#: Paths that exist in a report and must never reach the page. Each one is
#: asserted to still RESOLVE in its source, so a redaction that has stopped
#: applying is a failure rather than a comment nobody notices.
REDACTED = (
    Redaction(
        "parity.json",
        ("realClip", "maxSpeedKmh"),
        "an absolute km/h from motorway-a40.webm, whose along-road scale is "
        "bracketed at -33 %/+0 %; the engine returns null for speed on that clip",
    ),
    Redaction(
        "parity.json",
        ("realClip", "speedsReported"),
        "a count of speeds for a clip that ships uncalibrated; publishing it "
        "would imply calibrated speeds exist for this footage",
    ),
    Redaction(
        "parity.json",
        ("realClip", "speedsWithheld"),
        "the same, from the other side of the same withheld figure",
    ),
)


# -- the model card ------------------------------------------------------------
#
# The int8 comparison is a measurement, and it lives in the model card's table
# rather than in reports/ because it was made about the browser export and ships
# beside it. Parsed rather than transcribed for the same reason everything else
# here is: a number typed onto the page is a number the bake cannot protect.

#: Each declared row: the card's own row label, the type of its cells, and the
#: columns that MUST carry a figure.
#:
#: The last element is the condition this second data source was accepted on. A
#: card with an em-dashed cell used to bake to ``null`` and exit 0, and the page
#: then printed that null into a published table -- so the parse has to refuse on
#: every declared cell, not only on the three the derived figures are computed
#: from. A silent fallback here turns "the card is a source because the parse
#: fails loudly" into a hole.
#:
#: ``recall against float32`` and ``mean IoU of matched boxes`` genuinely have no
#: float32 cell: they are measured AGAINST float32, so the reference has no value
#: of its own to state and the card writes an em dash. That is a declared shape,
#: which is why the required columns are named per row rather than assumed.
MODEL_CARD_ROWS = {
    "fileSizeBytes": ("File size", int, ("float32", "int8")),
    "detections": ("Detections over 40 frames", int, ("float32", "int8")),
    "recallAgainstFloat32": ("Recall against float32", float, ("int8",)),
    "meanIouOfMatched": ("Mean IoU of matched boxes", float, ("int8",)),
}

_NUMERAL = r"\d+(?:\.\d+)?"

MODEL_CARD_PROTOCOL = re.compile(
    rf"(?P<frames>\d+) frames sampled every (?P<stride>\d+)\w* from.*?"
    rf"confidence (?P<conf>{_NUMERAL}) and IoU (?P<iou>{_NUMERAL})",
    re.DOTALL,
)


#: A markdown footnote reference riding along in a table cell -- the card
#: carries one on the float32 file size, explaining a nine-byte difference
#: between two of its own tables. It is prose about the figure, not part of it.
_FOOTNOTE = re.compile(r"\[\^[^\]]+\]")


def _number(text: str, kind: type) -> object:
    """A figure out of a model-card cell, or a refusal.

    Spaces inside a numeral are the card's thousands separator (``10 667 814``),
    and an em dash marks a cell the comparison does not fill.
    """
    cleaned = _FOOTNOTE.sub("", text)
    for space in (" ", "\u00a0", "\u202f", "\u2009"):
        cleaned = cleaned.replace(space, "")
    cleaned = cleaned.replace(",", "").strip()
    cleaned = cleaned.removesuffix("B")
    if cleaned in {"—", "-", ""}:
        return None
    try:
        return kind(cleaned)
    except ValueError as error:
        raise SourceContractError(f"cannot read {text!r} as {kind.__name__}") from error


def read_model_card(text: str, origin: str) -> dict:
    """The int8-versus-float32 comparison, out of the card's own table.

    Anchored on the row labels rather than on row positions, and every declared
    row must be found: a card that is reworded refuses the export instead of
    publishing a table with a hole in it.
    """
    cells: dict[str, list[str]] = {}
    for line in text.splitlines():
        if not line.startswith("|"):
            continue
        parts = [part.strip() for part in line.strip().strip("|").split("|")]
        if len(parts) == 3:
            cells[parts[0]] = parts[1:]

    out: dict[str, object] = {}
    missing = []
    for key, (label, kind, _required) in MODEL_CARD_ROWS.items():
        if label not in cells:
            missing.append(label)
            continue
        float32, int8 = cells[label]
        out[key] = {
            "float32": _number(float32, kind),
            "int8": _number(int8, kind),
        }
    if missing:
        raise SourceContractError(
            f"{origin}: the int8 comparison table has no row labelled "
            f"{missing}; the export cannot publish a figure it cannot find"
        )

    # Every declared cell, not only the ones arithmetic reads. An emptied cell
    # used to bake to `null` and exit 0, and the architecture table then printed
    # it -- a hole in a published comparison, arriving through the source that was
    # accepted precisely because it would refuse loudly.
    empty = [
        f"{label} / {column}"
        for key, (label, _kind, required) in MODEL_CARD_ROWS.items()
        for column in required
        if cast(dict, out[key])[column] is None
    ]
    if empty:
        raise SourceContractError(
            f"{origin}: the int8 comparison table leaves {empty} empty, and the "
            f"page publishes every declared cell of it; a figure the card does "
            f"not carry is not a figure the site may print"
        )

    protocol = MODEL_CARD_PROTOCOL.search(text)
    if protocol is None:
        raise SourceContractError(
            f"{origin}: the int8 comparison states no protocol (frames sampled, "
            f"confidence, NMS IoU); a figure without one does not ship"
        )

    # The three cells the two derived figures below are computed from are a subset
    # of the required cells checked above, so by here they are known present. The
    # narrowing is for the type checker and for the arithmetic that follows.
    size = out["fileSizeBytes"]
    recall = out["recallAgainstFloat32"]
    assert isinstance(size, dict) and isinstance(recall, dict)

    return {
        "source": "web/public/models/MODEL_CARD.md",
        "sampledFrames": int(protocol.group("frames")),
        "sampleStride": int(protocol.group("stride")),
        "confidence": float(protocol.group("conf")),
        "nmsIou": float(protocol.group("iou")),
        **out,
        # Derived, and stated as such: the two headline figures of the refusal.
        # bytesSaved is the difference of the two measured sizes;
        # detectionsLostFraction is one minus the measured recall.
        "bytesSaved": size["float32"] - size["int8"],
        "detectionsLostFraction": 1.0 - recall["int8"],
    }


# -- enforcing the redactions --------------------------------------------------

#: A step that stands for "every index of this list" or "every key of this
#: object" -- what Rows and Keyed expand over. Path comparison has to treat one
#: as matching anything, or a redaction inside a row would look unreachable.
WILDCARD = "*"


def declared_paths(fields: tuple, base: Path_ = ()):
    """Every source path the spec reads, with Rows/Keyed expansions wildcarded."""
    for field in fields:
        if isinstance(field, Derived):
            for path in field.inputs:
                yield base + path
            continue
        path = base + field.path
        if isinstance(field, (Value, Series)):
            yield path
        elif isinstance(field, Group):
            yield from declared_paths(field.fields, path)
        elif isinstance(field, (Rows, Keyed)):
            yield from declared_paths(field.fields, path + (WILDCARD,))
        else:  # pragma: no cover -- the vocabulary is closed
            raise SourceContractError(f"unknown field kind {field!r}")


def paths_overlap(declared: Path_, redacted: Path_) -> bool:
    """Whether one path could reach the other's value.

    True when either is a prefix of the other under wildcard matching: a field
    declared at ``realClip`` publishes everything beneath it, and a field
    declared at ``realClip/maxSpeedKmh`` publishes the redacted value itself.
    """
    for mine, theirs in zip(declared, redacted):
        if mine == WILDCARD or theirs == WILDCARD:
            continue
        if mine != theirs:
            return False
    return True


def keys_in(value: object, out: set | None = None) -> set:
    out = set() if out is None else out
    if isinstance(value, dict):
        for key, item in value.items():
            out.add(key)
            keys_in(item, out)
    elif isinstance(value, list):
        for item in value:
            keys_in(item, out)
    return out


#: Below this many characters a JSON literal is too common to search for -- a
#: small integer like `473` occurs all over a report as a frame index or a
#: detection count, and a substring guard on it would refuse every honest bake.
#: The structural check below is what protects those; the textual one is a second
#: line of defence for the distinctive figures, which is where it earns its keep.
DISTINCTIVE_LITERAL = 8


def enforce_redactions(
    reports: dict[str, object], baked: dict[str, object], body: str
) -> None:
    """Three checks, because one is not enough.

    Structural: no declared field may reach a redacted path. This is the one that
    actually holds -- it reasons about the spec rather than about the output text.

    By name: the redacted leaf name must not appear as a key anywhere in the
    output, so a later field cannot arrive at the same figure under the same name
    by another route.

    Textual: a distinctive literal must not appear in the rendered file at all.
    Belt and braces, and the reason the prohibition is worth enforcing here: this
    one figure must not reach the page by any path, including one nobody
    anticipated when writing the spec.

    Every redaction must also still RESOLVE in its source. A redaction for a key
    that has gone is a stale rule, and leaving it in place would quietly stop
    protecting anything.
    """
    output_keys = keys_in(baked)
    for redaction in REDACTED:
        source = reports.get(redaction.file)
        if source is None:
            raise SourceContractError(
                f"{redaction.file} is redacted from but is not in reports/"
            )
        value = resolve(source, redaction.path, redaction.file)
        check_scalar(value, f"{redaction.file}:{pointer(redaction.path)}")

        report = next(r for r in PUBLISHED if r.file == redaction.file)
        for declared in declared_paths(report.fields):
            if paths_overlap(declared, redaction.path):
                raise SourceContractError(
                    f"{redaction.file}: the spec reads {pointer(declared)}, which "
                    f"reaches the redacted {pointer(redaction.path)}. It is "
                    f"redacted because {redaction.reason}."
                )

        leaf = str(redaction.path[-1])
        if leaf in output_keys:
            raise SourceContractError(
                f"{redaction.file}: the output carries a key named {leaf!r}, which "
                f"is the redacted {pointer(redaction.path)}. It is redacted "
                f"because {redaction.reason}."
            )

        literal = json.dumps(value)
        if len(literal) >= DISTINCTIVE_LITERAL and literal in body:
            raise SourceContractError(
                f"{redaction.file}:{pointer(redaction.path)} reached the output as "
                f"{literal}. It is redacted because {redaction.reason}."
            )


# -- rendering -----------------------------------------------------------------


def render(reports: dict[str, object], model_card: str) -> str:
    """The whole TypeScript file, as a pure function of its inputs."""
    declared = {report.file for report in PUBLISHED}
    present = set(reports)
    if declared != present:
        undeclared = sorted(present - declared)
        absent = sorted(declared - present)
        raise SourceContractError(
            "reports/ and the PUBLISHED spec disagree. "
            + (f"Not declared: {undeclared}. " if undeclared else "")
            + (f"Declared but missing: {absent}. " if absent else "")
            + "A benchmark that is not declared would never reach the site, and "
            "the artefact would still regenerate byte-identically."
        )

    baked: dict[str, object] = {}
    for report in PUBLISHED:
        document = reports[report.file]
        section = project(document, report.fields, report.file)
        section["source"] = f"reports/{report.file}"
        baked[report.key] = section

    baked["model"] = read_model_card(model_card, "MODEL_CARD.md")

    body = json.dumps(baked, indent=2, ensure_ascii=False, allow_nan=False)
    enforce_redactions(reports, baked, body)

    lines = [
        HEADER.rstrip("\n"),
        "",
        "/** Every measured figure the results sections print, baked from the",
        " * reports named in each section's `source` field. Read from here and",
        " * never retyped: a figure typed into markup is one the bake cannot",
        " * keep in step with the measurement. */",
        f"export const REPORTS = {body} as const;",
        "",
        "export type Reports = typeof REPORTS;",
    ]
    return "\n".join(lines) + "\n"


def read_reports(directory: Path) -> dict[str, object]:
    """Every ``*.json`` directly inside ``directory``, keyed by file name.

    Sorted, so the read order is a property of the names rather than of the
    filesystem -- the output has to be reproducible on another machine.
    """
    if not directory.is_dir():
        raise SourceContractError(f"{directory} is not a directory")
    found = {}
    for path in sorted(directory.glob("*.json")):
        try:
            found[path.name] = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as error:
            raise SourceContractError(f"{path.name}: {error}") from error
    if not found:
        raise SourceContractError(f"{directory} holds no report files")
    return found


def parse_args(argv=None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate web/src/generated/reports.ts from reports/*.json."
    )
    parser.add_argument("--reports", default=str(DEFAULT_REPORTS))
    parser.add_argument("--model-card", default=str(DEFAULT_MODEL_CARD))
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    return parser.parse_args(argv)


def main(argv=None) -> int:
    args = parse_args(argv)
    out_path = Path(args.out)

    try:
        reports = read_reports(Path(args.reports))
        model_card = Path(args.model_card).read_text(encoding="utf-8")
        rendered = render(reports, model_card)
    except (SourceContractError, OSError) as error:
        print(
            f"refusing to bake the site data: every figure the page prints must "
            f"resolve to a value in reports/ or the model card, and nothing "
            f"redacted may reach the output.\n\n{error}",
            file=sys.stderr,
        )
        return 1

    out_path.parent.mkdir(parents=True, exist_ok=True)
    # newline="" so the "\n" endings survive on every platform: byte equality
    # with a fresh bake is the contract and the default would translate them.
    with open(out_path, "w", encoding="utf-8", newline="") as handle:
        handle.write(rendered)

    print(f"wrote {out_path} ({len(rendered.encode('utf-8'))} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
