#!/usr/bin/env python3
"""Generate the TypeScript mirror of the shared constants from the Python source.

``src/trafficlens/core/constants.py`` is the single definition of every tunable
both engines read. This script parses it with Python's ``ast`` module and writes
``web/src/generated/constants.ts``; ``tests/test_constants_sync.py`` regenerates
into a temp file and asserts byte equality with the committed artefact, so a
constant copied across the Python/TypeScript boundary by hand is a test failure
rather than a divergence nobody notices until the numbers disagree.

That matters because the browser engine's parity test asserts the two sides make
identical crossing decisions and agree on speeds to 1e-6. If a constant could
drift, parity would be comparing two different systems.

Usage:

    .venv/bin/python scripts/export_constants.py

The constants module is parsed as text and never imported, so the export does
not depend on the engine importing cleanly and no code in the source is ever
executed. That is also why the source is held to a deliberately narrow contract
-- module-level ``UPPER_CASE = <literal>`` assignments, comments, and the module
docstring, and nothing else. Anything that needs computing belongs at its point
of use. The parser refuses the whole file rather than skipping what it does not
understand: a silently dropped constant would still regenerate byte-identically,
which is exactly the failure the sync test exists to catch. That claim is held
up by two independent mechanisms -- every rule below rejects rather than skips,
and ``render`` asserts that the number of declarations it emitted equals the
number of constants the parser accepted.

Comments are carried across verbatim -- both the block above a constant and any
comment on its own line -- and constants keep their source order, so the
TypeScript reader gets the same reasoning, and the same file shape, the Python
reader gets, and the output is a pure function of the input.
"""

import argparse
import ast
import json
import math
import sys
from pathlib import Path
from typing import NamedTuple

ROOT = Path(__file__).resolve().parents[1]

DEFAULT_SOURCE = ROOT / "src" / "trafficlens" / "core" / "constants.py"
DEFAULT_OUT = ROOT / "web" / "src" / "generated" / "constants.ts"

HEADER = (
    "// generated by scripts/export_constants.py — do not edit\n"
    "//\n"
    "// Source of truth: src/trafficlens/core/constants.py\n"
    "// Change a value there and run the exporter; tests/test_constants_sync.py\n"
    "// fails while this file and that one disagree.\n"
)


class SourceContractError(Exception):
    """The constants source contains something the narrow contract forbids."""


def _is_docstring(node: ast.stmt) -> bool:
    return (
        isinstance(node, ast.Expr)
        and isinstance(node.value, ast.Constant)
        and isinstance(node.value.value, str)
    )


class Constant(NamedTuple):
    """One exported constant, and the source lines it occupies."""

    name: str
    value: object
    first_line: int
    last_line: int
    #: A comment on the assignment's own line, kept verbatim including its "#".
    trailing_comment: str


def parse_constants(source: str, origin: str) -> list[Constant]:
    """Every constant in ``source``.

    Raises ``SourceContractError`` listing every offending line at once, so a
    source that has drifted is fixed in one pass rather than one error per run.
    Each message names the actual rule that was broken, because the next person
    to hit one will be trying to add a constant, not debug this script.
    """
    lines = source.splitlines()
    module = ast.parse(source)
    constants: list[Constant] = []
    problems: list[str] = []

    for index, node in enumerate(module.body):
        if index == 0 and _is_docstring(node):
            continue
        if isinstance(node, ast.AnnAssign):
            # Reported separately from the multi-target case: an annotation is
            # not a second target, and "only single-target assignments are
            # allowed" would send the reader looking for a target that is not
            # there.
            annotated = getattr(node.target, "id", "the constant")
            problems.append(
                f"{origin}:{node.lineno}: {annotated} has a type annotation, "
                f"which is not supported; write NAME = <literal> instead"
            )
            continue
        if not isinstance(node, ast.Assign):
            problems.append(
                f"{origin}:{node.lineno}: only assignments are allowed here, "
                f"found {type(node).__name__}"
            )
            continue
        if len(node.targets) != 1:
            problems.append(
                f"{origin}:{node.lineno}: chained assignment is not supported; "
                f"give each constant its own statement"
            )
            continue
        (target,) = node.targets
        if not isinstance(target, ast.Name):
            problems.append(f"{origin}:{node.lineno}: assignment target must be a name")
            continue
        name = target.id
        if name != name.upper() or not name[0].isalpha():
            problems.append(f"{origin}:{node.lineno}: {name} is not UPPER_CASE")
            continue
        if _is_negated_literal(node.value):
            # Deliberately unsupported rather than accidentally: a negated
            # literal is an ast.UnaryOp, and widening the parser to unwrap one
            # is the first step towards evaluating expressions. Named
            # explicitly because to a human "-1.5" plainly IS a float literal.
            problems.append(
                f"{origin}:{node.lineno}: {name} is a negated literal, which is "
                f"an expression rather than a literal and is not supported; "
                f"move the sign to the point of use"
            )
            continue
        if not isinstance(node.value, ast.Constant):
            # Covers computed expressions, tuples, f-strings and name
            # references alike. Widening this is the wrong fix: move the
            # computation to its point of use instead.
            problems.append(
                f"{origin}:{node.lineno}: {name} is not a plain literal "
                f"(int, float, str or bool)"
            )
            continue
        value = node.value.value
        if not isinstance(value, (bool, int, float, str)):
            problems.append(
                f"{origin}:{node.lineno}: {name} has unsupported literal type "
                f"{type(value).__name__}"
            )
            continue
        if isinstance(value, float) and not math.isfinite(value):
            # repr() would emit `inf` or `nan`, neither of which is a valid
            # TypeScript number literal, so this would produce a file that
            # does not compile.
            problems.append(f"{origin}:{node.lineno}: {name} is not finite")
            continue

        first_line = node.lineno
        last_line = node.end_lineno or first_line
        if node.col_offset != 0:
            # A second statement on a line already claimed by another one. The
            # renderer keys constants by their starting line, so this would
            # silently drop whichever lost the collision -- the hand-picked
            # subset the whole exporter exists to make impossible.
            problems.append(
                f"{origin}:{first_line}: {name} does not start its own line; "
                f"put one constant on each line"
            )
            continue
        # ast reports col_offset/end_col_offset as UTF-8 BYTE offsets, so the
        # line has to be sliced as bytes. Slicing the str instead overshoots by
        # one position per non-ASCII character already on the line, which
        # rejects a legal constant while quoting text that is not there.
        trailing = (
            lines[last_line - 1]
            .encode("utf-8")[node.end_col_offset :]
            .decode("utf-8")
            .strip()
        )
        if trailing and not trailing.startswith("#"):
            problems.append(
                f"{origin}:{last_line}: {name} shares its line with {trailing!r}; "
                f"put one constant on each line"
            )
            continue

        constants.append(Constant(name, value, first_line, last_line, trailing))

    if problems:
        raise SourceContractError("\n".join(problems))
    return constants


def _is_negated_literal(node: ast.expr) -> bool:
    return (
        isinstance(node, ast.UnaryOp)
        and isinstance(node.op, (ast.USub, ast.UAdd))
        and isinstance(node.operand, ast.Constant)
    )


def to_typescript_literal(value: object) -> str:
    """A TypeScript literal that parses to exactly the same value.

    Both languages store these as IEEE-754 doubles and ``repr`` gives the
    shortest string that round-trips, so the emitted literal is exact rather
    than merely close -- which is what lets the parity test compare the two
    engines without an epsilon on the constants themselves.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value)
    raise SourceContractError(f"cannot express {type(value).__name__} in TypeScript")


def render(source: str, origin: str) -> str:
    """The full TypeScript file for ``source``.

    Walks the source line by line rather than emitting from the parsed nodes
    alone, because ``ast`` discards comments and the reasoning behind several of
    these values -- the Mahalanobis gate, the association floor, the speed
    window -- is worth more than the numbers. Source order is preserved, so the
    output is deterministic without needing a sort.
    """
    constants = parse_constants(source, origin)
    starts = {constant.first_line: constant for constant in constants}
    consumed = {
        line
        for constant in constants
        for line in range(constant.first_line + 1, constant.last_line + 1)
    }

    module = ast.parse(source)
    if module.body and _is_docstring(module.body[0]):
        docstring = module.body[0]
        consumed.update(range(docstring.lineno, (docstring.end_lineno or 0) + 1))

    out: list[str] = [HEADER.rstrip("\n")]
    emitted = 0
    for number, line in enumerate(source.splitlines(), start=1):
        if number in consumed:
            continue
        if number in starts:
            constant = starts[number]
            declaration = (
                f"export const {constant.name} = "
                f"{to_typescript_literal(constant.value)};"
            )
            if constant.trailing_comment:
                declaration += "  " + constant.trailing_comment.replace("#", "//", 1)
            out.append(declaration)
            emitted += 1
        elif not line.strip():
            out.append("")
        elif line.lstrip().startswith("#"):
            # The first "#" is the comment marker, since it is the line's first
            # non-space character; replacing only it keeps any indentation.
            out.append(line.rstrip().replace("#", "//", 1))
        else:
            # parse_constants() accepted the source, so nothing else can be
            # here -- but never emit a line silently misread as something else.
            raise SourceContractError(f"{origin}:{number}: unexpected line {line!r}")

    if emitted != len(constants):
        # Structural backstop, independent of every rule above: if the parser
        # accepted N constants, exactly N declarations must reach the output.
        # Anything that collapses two constants onto one emission -- a keying
        # collision, a rule added later that forgets this invariant -- fails
        # here rather than shipping a silent subset that regenerates
        # byte-identically and so passes the sync test.
        raise SourceContractError(
            f"{origin}: emitted {emitted} declarations for {len(constants)} "
            f"parsed constants; the export would be a silent subset"
        )

    while out and out[-1] == "":
        out.pop()
    return "\n".join(out) + "\n"


def parse_args(argv=None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate web/src/generated/constants.ts from the Python core."
    )
    parser.add_argument(
        "--source",
        default=str(DEFAULT_SOURCE),
        help="the Python constants module to read",
    )
    parser.add_argument(
        "--out",
        default=str(DEFAULT_OUT),
        help="the TypeScript file to write",
    )
    return parser.parse_args(argv)


def main(argv=None) -> int:
    args = parse_args(argv)
    source_path = Path(args.source)
    out_path = Path(args.out)

    try:
        rendered = render(source_path.read_text(encoding="utf-8"), source_path.name)
    except SourceContractError as error:
        print(
            f"refusing to export {source_path}: it must contain only module-level\n"
            f"UPPER_CASE = <literal> assignments, comments and a docstring.\n"
            f"Move anything computed to its point of use.\n\n{error}",
            file=sys.stderr,
        )
        return 1

    out_path.parent.mkdir(parents=True, exist_ok=True)
    # Explicit newline="" so the "\n" line endings survive on every platform;
    # byte equality is the contract and the default would translate them.
    with open(out_path, "w", encoding="utf-8", newline="") as handle:
        handle.write(rendered)

    # Counted from what was actually written, not from a second parse.
    exported = sum(1 for line in rendered.splitlines() if line.startswith("export const "))
    print(f"wrote {out_path} ({exported} constants)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
