#!/usr/bin/env python3
"""Generate the TypeScript mirror of the shared constants from the Python source.

``src/trafficlens/core/constants.py`` is the single definition of every tunable
both engines read. This script parses it with Python's ``ast`` module and writes
``web/src/generated/constants.ts``; ``tests/test_constants_sync.py`` regenerates
into a temp file and asserts byte equality with the committed artefact, so a
constant copied across the Python/TypeScript boundary by hand is a test failure
rather than a divergence nobody notices until the numbers disagree.

That matters because the browser engine's parity test asserts the two sides make
identical crossing decisions and agree on speeds to 1e-6. If a constant could
drift, parity would be comparing two different systems.

Usage:

    .venv/bin/python scripts/export_constants.py

The constants module is parsed as text and never imported, so the export does
not depend on the engine importing cleanly and no code in the source is ever
executed. That is also why the source is held to a deliberately narrow contract
-- module-level ``UPPER_CASE = <literal>`` assignments, comments, and the module
docstring, and nothing else. Anything that needs computing belongs at its point
of use. The parser refuses the whole file rather than skipping what it does not
understand: a silently dropped constant would still regenerate byte-identically,
which is exactly the failure the sync test exists to catch.

Comments are carried across verbatim, and constants keep their source order, so
the TypeScript reader gets the same reasoning -- and the same file shape -- the
Python reader gets, and the output is a pure function of the input.
"""

import argparse
import ast
import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

DEFAULT_SOURCE = ROOT / "src" / "trafficlens" / "core" / "constants.py"
DEFAULT_OUT = ROOT / "web" / "src" / "generated" / "constants.ts"

HEADER = (
    "// generated by scripts/export_constants.py — do not edit\n"
    "//\n"
    "// Source of truth: src/trafficlens/core/constants.py\n"
    "// Change a value there and run the exporter; tests/test_constants_sync.py\n"
    "// fails while this file and that one disagree.\n"
)


class SourceContractError(Exception):
    """The constants source contains something the narrow contract forbids."""


def _is_docstring(node: ast.stmt) -> bool:
    return (
        isinstance(node, ast.Expr)
        and isinstance(node.value, ast.Constant)
        and isinstance(node.value.value, str)
    )


def parse_constants(source: str, origin: str) -> list[tuple[str, object, int, int]]:
    """Every constant in ``source`` as ``(name, value, first_line, last_line)``.

    Raises ``SourceContractError`` listing every offending line at once, so a
    source that has drifted is fixed in one pass rather than one error per run.
    """
    module = ast.parse(source)
    constants: list[tuple[str, object, int, int]] = []
    problems: list[str] = []

    for index, node in enumerate(module.body):
        if index == 0 and _is_docstring(node):
            continue
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            problems.append(
                f"{origin}:{node.lineno}: only single-target assignments are allowed"
            )
            continue
        (target,) = node.targets
        if not isinstance(target, ast.Name):
            problems.append(f"{origin}:{node.lineno}: assignment target must be a name")
            continue
        name = target.id
        if name != name.upper() or not name[0].isalpha():
            problems.append(f"{origin}:{node.lineno}: {name} is not UPPER_CASE")
            continue
        if not isinstance(node.value, ast.Constant):
            # Covers computed expressions, tuples, f-strings, negated literals
            # and name references alike. Widening this is the wrong fix: move
            # the computation to its point of use instead.
            problems.append(
                f"{origin}:{node.lineno}: {name} is not a plain literal "
                f"(int, float, str or bool)"
            )
            continue
        value = node.value.value
        if not isinstance(value, (bool, int, float, str)):
            problems.append(
                f"{origin}:{node.lineno}: {name} has unsupported literal type "
                f"{type(value).__name__}"
            )
            continue
        if isinstance(value, float) and not math.isfinite(value):
            # repr() would emit `inf` or `nan`, neither of which is a valid
            # TypeScript number literal, so this would produce a file that
            # does not compile.
            problems.append(f"{origin}:{node.lineno}: {name} is not finite")
            continue
        constants.append((name, value, node.lineno, node.end_lineno or node.lineno))

    if problems:
        raise SourceContractError("\n".join(problems))
    return constants


def to_typescript_literal(value: object) -> str:
    """A TypeScript literal that parses to exactly the same value.

    Both languages store these as IEEE-754 doubles and ``repr`` gives the
    shortest string that round-trips, so the emitted literal is exact rather
    than merely close -- which is what lets the parity test compare the two
    engines without an epsilon on the constants themselves.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value)
    raise SourceContractError(f"cannot express {type(value).__name__} in TypeScript")


def render(source: str, origin: str) -> str:
    """The full TypeScript file for ``source``.

    Walks the source line by line rather than emitting from the parsed nodes
    alone, because ``ast`` discards comments and the reasoning behind several of
    these values -- the Mahalanobis gate, the association floor, the speed
    window -- is worth more than the numbers. Source order is preserved, so the
    output is deterministic without needing a sort.
    """
    constants = parse_constants(source, origin)
    starts = {lineno: (name, value) for name, value, lineno, _ in constants}
    consumed = {
        line
        for _, _, first, last in constants
        for line in range(first + 1, last + 1)
    }

    module = ast.parse(source)
    if module.body and _is_docstring(module.body[0]):
        docstring = module.body[0]
        consumed.update(range(docstring.lineno, (docstring.end_lineno or 0) + 1))

    out: list[str] = [HEADER.rstrip("\n")]
    for number, line in enumerate(source.splitlines(), start=1):
        if number in consumed:
            continue
        if number in starts:
            name, value = starts[number]
            out.append(f"export const {name} = {to_typescript_literal(value)};")
        elif not line.strip():
            out.append("")
        elif line.lstrip().startswith("#"):
            # The first "#" is the comment marker, since it is the line's first
            # non-space character; replacing only it keeps any indentation.
            out.append(line.rstrip().replace("#", "//", 1))
        else:
            # parse_constants() accepted the source, so nothing else can be
            # here -- but never emit a line silently misread as something else.
            raise SourceContractError(f"{origin}:{number}: unexpected line {line!r}")

    while out and out[-1] == "":
        out.pop()
    return "\n".join(out) + "\n"


def parse_args(argv=None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate web/src/generated/constants.ts from the Python core."
    )
    parser.add_argument(
        "--source",
        default=str(DEFAULT_SOURCE),
        help="the Python constants module to read",
    )
    parser.add_argument(
        "--out",
        default=str(DEFAULT_OUT),
        help="the TypeScript file to write",
    )
    return parser.parse_args(argv)


def main(argv=None) -> int:
    args = parse_args(argv)
    source_path = Path(args.source)
    out_path = Path(args.out)

    try:
        rendered = render(source_path.read_text(encoding="utf-8"), source_path.name)
    except SourceContractError as error:
        print(
            f"refusing to export {source_path}: it must contain only module-level\n"
            f"UPPER_CASE = <literal> assignments, comments and a docstring.\n"
            f"Move anything computed to its point of use.\n\n{error}",
            file=sys.stderr,
        )
        return 1

    out_path.parent.mkdir(parents=True, exist_ok=True)
    # Explicit newline="" so the "\n" line endings survive on every platform;
    # byte equality is the contract and the default would translate them.
    with open(out_path, "w", encoding="utf-8", newline="") as handle:
        handle.write(rendered)

    # Counted from what was actually written, not from a second parse.
    exported = sum(1 for line in rendered.splitlines() if line.startswith("export const "))
    print(f"wrote {out_path} ({exported} constants)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
